//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 06:36:32 PM WAT 
//


package com.seamfix.nimc.jaxb.enrollment.update;

import java.math.BigDecimal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="APPLICANT_NAME" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TITLE" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="mr"/>
 *                         &lt;enumeration value="ms"/>
 *                         &lt;enumeration value="mrs"/>
 *                         &lt;enumeration value="miss"/>
 *                         &lt;enumeration value="master"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="SURNAME">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="40"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="FIRST_NAME">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="40"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="MIDDLE_NAME" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;maxLength value="40"/>
 *                         &lt;minLength value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MAIDEN_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OTHER_NAMES" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NATIONALITY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *               &lt;minLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BIRTH_DATE_VERIFY_P" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="v"/>
 *               &lt;enumeration value="a"/>
 *               &lt;enumeration value="d"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MARITAL_STATUS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="married"/>
 *               &lt;enumeration value="single"/>
 *               &lt;enumeration value="separated"/>
 *               &lt;enumeration value="divorced"/>
 *               &lt;enumeration value="widowed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SPOUSE_IDENTIFICATION_NUMBER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="11"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="00000000000"/>
 *               &lt;maxExclusive value="100000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HEIGHT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="3"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="0"/>
 *               &lt;maxExclusive value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESIDENCE_STATUS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="naturalisation"/>
 *               &lt;enumeration value="birth"/>
 *               &lt;enumeration value="registration"/>
 *               &lt;enumeration value="legalresidence"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RELIGION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EMAIL_ADDRESS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TELEPHONE_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NATIVE_SPOKEN_LANGUAGE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OTHER_SPOKEN_LANGUAGE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="READ_WRITE_LANGUAGE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="64"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EDUCATION_LEVEL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="none"/>
 *               &lt;enumeration value="primary"/>
 *               &lt;enumeration value="secondary"/>
 *               &lt;enumeration value="tertiary"/>
 *               &lt;enumeration value="post graduate"/>
 *               &lt;enumeration value="certification"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PROFESSION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EMPLOYMENT_STATUS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="unemployed"/>
 *               &lt;enumeration value="employed"/>
 *               &lt;enumeration value="pensioner"/>
 *               &lt;enumeration value="self employed"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HOMELESS_P" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="t"/>
 *               &lt;enumeration value="f"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "applicantname",
        "maidenname",
        "othernames",
        "nationality",
        "birthdate",
        "birthdateverifyp",
        "maritalstatus",
        "spouseidentificationnumber",
        "height",
        "residencestatus",
        "religion",
        "emailaddress",
        "telephoneno",
        "nativespokenlanguage",
        "otherspokenlanguage",
        "readwritelanguage",
        "educationlevel",
        "profession",
        "employmentstatus",
        "homelessp"
})
@SuppressWarnings("PMD.ExcessivePublicCount")
public class DEMOGRAPHICDATA {

    @XmlElement(name = "APPLICANT_NAME", required = false)
    public APPLICANTNAME applicantname;
    @XmlElement(name = "MAIDEN_NAME", required = false)
    public String maidenname;
    @XmlElement(name = "OTHER_NAMES", required = false)
    public String othernames;
    @XmlElement(name = "NATIONALITY", required = false)
    public String nationality;
    @XmlElement(name = "BIRTH_DATE_VERIFY_P",required = false)
    public String birthdateverifyp;
    @XmlElement(name = "MARITAL_STATUS",required = false)
    public String maritalstatus;
    @XmlElement(name = "SPOUSE_IDENTIFICATION_NUMBER", required = false)
    public BigDecimal spouseidentificationnumber;
    @XmlElement(name = "HEIGHT", required = false)
    public BigDecimal height;
    @XmlElement(name = "RESIDENCE_STATUS", required = false)
    public String residencestatus;
    @XmlElement(name = "RELIGION", required = false)
    public String religion;
    @XmlElement(name = "EMAIL_ADDRESS", required = false)
    public String emailaddress;
    @XmlElement(name = "TELEPHONE_NO", required = false)
    public String telephoneno;
    @XmlElement(name = "NATIVE_SPOKEN_LANGUAGE",required = false)
    public String nativespokenlanguage;
    @XmlElement(name = "OTHER_SPOKEN_LANGUAGE", required = false)
    public String otherspokenlanguage;
    @XmlElement(name = "READ_WRITE_LANGUAGE", required = false)
    public String readwritelanguage;
    @XmlElement(name = "EDUCATION_LEVEL",required = false)
    public String educationlevel;
    @XmlElement(name = "PROFESSION", required = false)
    public String profession;
    @XmlElement(name = "EMPLOYMENT_STATUS", required = false)
    public String employmentstatus;
    @XmlElement(name = "HOMELESS_P", required = false)
    public String homelessp;
    @XmlElement(name = "BIRTH_DATE")
    public String birthdate;

    /**
     * Gets the value of the applicantname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link APPLICANTNAME }{@code >}
     *     
     */
    public APPLICANTNAME getAPPLICANTNAME() {
        return applicantname;
    }

    /**
     * Sets the value of the applicantname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link APPLICANTNAME }{@code >}
     *     
     */
    public void setAPPLICANTNAME(APPLICANTNAME  value) {
        this.applicantname = value;
    }

    /**
     * Gets the value of the maidenname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getMAIDENNAME() {
        return maidenname;
    }

    /**
     * Sets the value of the maidenname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMAIDENNAME(String  value) {
        this.maidenname = value;
    }

    /**
     * Gets the value of the othernames property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getOTHERNAMES() {
        return othernames;
    }

    /**
     * Sets the value of the othernames property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOTHERNAMES(String  value) {
        this.othernames = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getNATIONALITY() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNATIONALITY(String  value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the birthdateverifyp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getBIRTHDATEVERIFYP() {
        return birthdateverifyp;
    }

    /**
     * Sets the value of the birthdateverifyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setBIRTHDATEVERIFYP(String  value) {
        this.birthdateverifyp = value;
    }

    /**
     * Gets the value of the maritalstatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getMARITALSTATUS() {
        return maritalstatus;
    }

    /**
     * Sets the value of the maritalstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMARITALSTATUS(String  value) {
        this.maritalstatus = value;
    }

    /**
     * Gets the value of the spouseidentificationnumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public BigDecimal getSPOUSEIDENTIFICATIONNUMBER() {
        return spouseidentificationnumber;
    }

    /**
     * Sets the value of the spouseidentificationnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setSPOUSEIDENTIFICATIONNUMBER(BigDecimal  value) {
        this.spouseidentificationnumber = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public BigDecimal getHEIGHT() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setHEIGHT(BigDecimal  value) {
        this.height = value;
    }

    /**
     * Gets the value of the residencestatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getRESIDENCESTATUS() {
        return residencestatus;
    }

    /**
     * Sets the value of the residencestatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRESIDENCESTATUS(String  value) {
        this.residencestatus = value;
    }

    /**
     * Gets the value of the religion property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getRELIGION() {
        return religion;
    }

    /**
     * Sets the value of the religion property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setRELIGION(String  value) {
        this.religion = value;
    }

    /**
     * Gets the value of the emailaddress property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getEMAILADDRESS() {
        return emailaddress;
    }

    /**
     * Sets the value of the emailaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEMAILADDRESS(String  value) {
        this.emailaddress = value;
    }

    /**
     * Gets the value of the telephoneno property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getTELEPHONENO() {
        return telephoneno;
    }

    /**
     * Sets the value of the telephoneno property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTELEPHONENO(String  value) {
        this.telephoneno = value;
    }

    /**
     * Gets the value of the nativespokenlanguage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getNATIVESPOKENLANGUAGE() {
        return nativespokenlanguage;
    }

    /**
     * Sets the value of the nativespokenlanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNATIVESPOKENLANGUAGE(String  value) {
        this.nativespokenlanguage = value;
    }

    /**
     * Gets the value of the otherspokenlanguage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getOTHERSPOKENLANGUAGE() {
        return otherspokenlanguage;
    }

    /**
     * Sets the value of the otherspokenlanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setOTHERSPOKENLANGUAGE(String  value) {
        this.otherspokenlanguage = value;
    }

    /**
     * Gets the value of the readwritelanguage property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getREADWRITELANGUAGE() {
        return readwritelanguage;
    }

    /**
     * Sets the value of the readwritelanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setREADWRITELANGUAGE(String  value) {
        this.readwritelanguage = value;
    }

    /**
     * Gets the value of the educationlevel property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getEDUCATIONLEVEL() {
        return educationlevel;
    }

    /**
     * Sets the value of the educationlevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEDUCATIONLEVEL(String  value) {
        this.educationlevel = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getPROFESSION() {
        return profession;
    }

    /**
     * Sets the value of the profession property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPROFESSION(String  value) {
        this.profession = value;
    }

    /**
     * Gets the value of the employmentstatus property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getEMPLOYMENTSTATUS() {
        return employmentstatus;
    }

    /**
     * Sets the value of the employmentstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setEMPLOYMENTSTATUS(String  value) {
        this.employmentstatus = value;
    }

    /**
     * Gets the value of the homelessp property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getHOMELESSP() {
        return homelessp;
    }

    /**
     * Sets the value of the homelessp property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setHOMELESSP(String  value) {
        this.homelessp = value;
    }

    /**
     * Gets the value of the birthdate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBIRTHDATE() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBIRTHDATE(String value) {
        this.birthdate = value;
    }

}
