//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 06:36:32 PM WAT 
//


package com.seamfix.nimc.jaxb.enrollment.update;

import java.math.BigDecimal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MOTHER_SURNAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOTHER_FIRST_NAME">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOTHER_MIDDLE_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOTHER_MAIDEN_NAME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *               &lt;minLength value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOTHER_IDENTIFICATION_NUMBER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="11"/>
 *               &lt;fractionDigits value="0"/>
 *               &lt;minExclusive value="00000000000"/>
 *               &lt;maxExclusive value="100000000000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mothersurname",
    "motherfirstname",
    "mothermiddlename",
    "mothermaidenname",
    "motheridentificationnumber"
})
public class MOTHERDATA {

    @XmlElement(name = "MOTHER_SURNAME", required = true)
    public String mothersurname;
    @XmlElement(name = "MOTHER_FIRST_NAME", required = true)
    public String motherfirstname;
    @XmlElement(name = "MOTHER_MIDDLE_NAME", required = false)
    public String mothermiddlename;
    @XmlElement(name = "MOTHER_MAIDEN_NAME", required = false)
    public String mothermaidenname;
    @XmlElement(name = "MOTHER_IDENTIFICATION_NUMBER", required = false)
    public BigDecimal motheridentificationnumber;

    /**
     * Gets the value of the mothersurname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTHERSURNAME() {
        return mothersurname;
    }

    /**
     * Sets the value of the mothersurname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTHERSURNAME(String value) {
        this.mothersurname = value;
    }

    /**
     * Gets the value of the motherfirstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOTHERFIRSTNAME() {
        return motherfirstname;
    }

    /**
     * Sets the value of the motherfirstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOTHERFIRSTNAME(String value) {
        this.motherfirstname = value;
    }

    /**
     * Gets the value of the mothermiddlename property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getMOTHERMIDDLENAME() {
        return mothermiddlename;
    }

    /**
     * Sets the value of the mothermiddlename property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMOTHERMIDDLENAME(String value) {
        this.mothermiddlename = value;
    }

    /**
     * Gets the value of the mothermaidenname property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getMOTHERMAIDENNAME() {
        return mothermaidenname;
    }

    /**
     * Sets the value of the mothermaidenname property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMOTHERMAIDENNAME(String value) {
        this.mothermaidenname = value;
    }

    /**
     * Gets the value of the motheridentificationnumber property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public BigDecimal getMOTHERIDENTIFICATIONNUMBER() {
        return motheridentificationnumber;
    }

    /**
     * Sets the value of the motheridentificationnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     *     
     */
    public void setMOTHERIDENTIFICATIONNUMBER(BigDecimal value) {
        this.motheridentificationnumber = value;
    }

}
