//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.05 at 06:36:32 PM WAT 
//


package com.seamfix.nimc.jaxb.enrollment.update;

import java.math.BigDecimal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@SuppressWarnings({"PMD.ExcessivePublicCount","PMD.TooManyMethods"})
public class ObjectFactory {

    private final static QName _BIOMETRICDATALEFTRINGQUALITY_QNAME = new QName("", "LEFT_RING_QUALITY");
    private final static QName _BIOMETRICDATARIGHTMIDDLE_QNAME = new QName("", "RIGHT_MIDDLE");
    private final static QName _BIOMETRICDATALEFTTHUMB_QNAME = new QName("", "LEFT_THUMB");
    private final static QName _BIOMETRICDATARIGHTRING_QNAME = new QName("", "RIGHT_RING");
    private final static QName _BIOMETRICDATALEFTRING_QNAME = new QName("", "LEFT_RING");
    private final static QName _BIOMETRICDATARIGHTMIDDLEQUALITY_QNAME = new QName("", "RIGHT_MIDDLE_QUALITY");
    private final static QName _BIOMETRICDATAUSERID_QNAME = new QName("", "USER_ID");
    private final static QName _BIOMETRICDATALEFTTHUMBQUALITY_QNAME = new QName("", "LEFT_THUMB_QUALITY");
    private final static QName _BIOMETRICDATARIGHTRINGQUALITY_QNAME = new QName("", "RIGHT_RING_QUALITY");
    private final static QName _BIOMETRICDATALEFTMIDDLE_QNAME = new QName("", "LEFT_MIDDLE");
    private final static QName _BIOMETRICDATARIGHTLITTLE_QNAME = new QName("", "RIGHT_LITTLE");
    private final static QName _BIOMETRICDATALEFTINDEX_QNAME = new QName("", "LEFT_INDEX");
    private final static QName _BIOMETRICDATALEFTLITTLE_QNAME = new QName("", "LEFT_LITTLE");
    private final static QName _BIOMETRICDATARIGHTTHUMB_QNAME = new QName("", "RIGHT_THUMB");
    private final static QName _BIOMETRICDATALEFTLITTLEQUALITY_QNAME = new QName("", "LEFT_LITTLE_QUALITY");
    private final static QName _BIOMETRICDATARIGHTINDEXQUALITY_QNAME = new QName("", "RIGHT_INDEX_QUALITY");
    private final static QName _BIOMETRICDATALEFTINDEXQUALITY_QNAME = new QName("", "LEFT_INDEX_QUALITY");
    private final static QName _BIOMETRICDATARIGHTTHUMBQUALITY_QNAME = new QName("", "RIGHT_THUMB_QUALITY");
    private final static QName _BIOMETRICDATALEFTMIDDLEQUALITY_QNAME = new QName("", "LEFT_MIDDLE_QUALITY");
    private final static QName _BIOMETRICDATARIGHTINDEX_QNAME = new QName("", "RIGHT_INDEX");
    private final static QName _BIOMETRICDATARIGHTLITTLEQUALITY_QNAME = new QName("", "RIGHT_LITTLE_QUALITY");
    private final static QName _MOTHERDATAMOTHERMIDDLENAME_QNAME = new QName("", "MOTHER_MIDDLE_NAME");
    private final static QName _MOTHERDATAMOTHERMAIDENNAME_QNAME = new QName("", "MOTHER_MAIDEN_NAME");
    private final static QName _MOTHERDATAMOTHERIDENTIFICATIONNUMBER_QNAME = new QName("", "MOTHER_IDENTIFICATION_NUMBER");
    private final static QName _FATHERDATAFATHERMIDDLENAME_QNAME = new QName("", "FATHER_MIDDLE_NAME");
    private final static QName _FATHERDATAFATHERIDENTIFICATIONNUMBER_QNAME = new QName("", "FATHER_IDENTIFICATION_NUMBER");
    private final static QName _APPLICANTNAMETITLE_QNAME = new QName("", "TITLE");
    private final static QName _APPLICANTNAMEMIDDLENAME_QNAME = new QName("", "MIDDLE_NAME");
    private final static QName _ENROLLMENTDATADEMOGRAPHICDATA_QNAME = new QName("", "DEMOGRAPHIC_DATA");
    private final static QName _ENROLLMENTDATACARDFINANCIALDATA_QNAME = new QName("", "CARD_FINANCIAL_DATA");
    private final static QName _ENROLLMENTDATARESIDENCEADDRESSDATA_QNAME = new QName("", "RESIDENCE_ADDRESS_DATA");
    private final static QName _ENROLLMENTDATAPHYSICALFEATUREDATA_QNAME = new QName("", "PHYSICAL_FEATURE_DATA");
    private final static QName _ENROLLMENTDATANEXTOFKINDATA_QNAME = new QName("", "NEXT_OF_KIN_DATA");
    private final static QName _ENROLLMENTDATAAPPLICANTSIGNATURE_QNAME = new QName("", "APPLICANT_SIGNATURE");
    private final static QName _ENROLLMENTDATADISABILITYDATA_QNAME = new QName("", "DISABILITY_DATA");
    private final static QName _ENROLLMENTDATAPARENTDATA_QNAME = new QName("", "PARENT_DATA");
    private final static QName _ENROLLMENTDATAGUARDIANDATA_QNAME = new QName("", "GUARDIAN_DATA");
    private final static QName _RESIDENCEADDRESSDATAPOSTALCODE_QNAME = new QName("", "POSTAL_CODE");
    private final static QName _RESIDENCEADDRESSDATAADDRESSLINETWO_QNAME = new QName("", "ADDRESS_LINE_TWO");
    private final static QName _DEMOGRAPHICDATANATIONALITY_QNAME = new QName("", "NATIONALITY");
    private final static QName _DEMOGRAPHICDATAEMPLOYMENTSTATUS_QNAME = new QName("", "EMPLOYMENT_STATUS");
    private final static QName _DEMOGRAPHICDATABIRTHDATEVERIFYP_QNAME = new QName("", "BIRTH_DATE_VERIFY_P");
    private final static QName _DEMOGRAPHICDATAOTHERSPOKENLANGUAGE_QNAME = new QName("", "OTHER_SPOKEN_LANGUAGE");
    private final static QName _DEMOGRAPHICDATAREADWRITELANGUAGE_QNAME = new QName("", "READ_WRITE_LANGUAGE");
    private final static QName _DEMOGRAPHICDATAEDUCATIONLEVEL_QNAME = new QName("", "EDUCATION_LEVEL");
    private final static QName _DEMOGRAPHICDATAAPPLICANTNAME_QNAME = new QName("", "APPLICANT_NAME");
    private final static QName _DEMOGRAPHICDATAMARITALSTATUS_QNAME = new QName("", "MARITAL_STATUS");
    private final static QName _DEMOGRAPHICDATASPOUSEIDENTIFICATIONNUMBER_QNAME = new QName("", "SPOUSE_IDENTIFICATION_NUMBER");
    private final static QName _DEMOGRAPHICDATARESIDENCESTATUS_QNAME = new QName("", "RESIDENCE_STATUS");
    private final static QName _DEMOGRAPHICDATAHEIGHT_QNAME = new QName("", "HEIGHT");
    private final static QName _DEMOGRAPHICDATANATIVESPOKENLANGUAGE_QNAME = new QName("", "NATIVE_SPOKEN_LANGUAGE");
    private final static QName _DEMOGRAPHICDATAEMAILADDRESS_QNAME = new QName("", "EMAIL_ADDRESS");
    private final static QName _DEMOGRAPHICDATARELIGION_QNAME = new QName("", "RELIGION");
    private final static QName _DEMOGRAPHICDATAMAIDENNAME_QNAME = new QName("", "MAIDEN_NAME");
    private final static QName _DEMOGRAPHICDATAOTHERNAMES_QNAME = new QName("", "OTHER_NAMES");
    private final static QName _DEMOGRAPHICDATAPROFESSION_QNAME = new QName("", "PROFESSION");
    private final static QName _DEMOGRAPHICDATATELEPHONENO_QNAME = new QName("", "TELEPHONE_NO");
    private final static QName _DEMOGRAPHICDATAHOMELESSP_QNAME = new QName("", "HOMELESS_P");
    private final static QName _PARENTDATAFATHERDATA_QNAME = new QName("", "FATHER_DATA");
    private final static QName _PARENTDATAMOTHERDATA_QNAME = new QName("", "MOTHER_DATA");
    private final static QName _DOCUMENTDATADOCUMENTNUMBER_QNAME = new QName("", "DOCUMENT_NUMBER");
    private final static QName _DOCUMENTDATADOCUMENTEXPIRYDATE_QNAME = new QName("", "DOCUMENT_EXPIRY_DATE");
    private final static QName _NEXTOFKINDATATOWN_QNAME = new QName("", "TOWN");
    private final static QName _NEXTOFKINDATALGA_QNAME = new QName("", "LGA");
    private final static QName _NEXTOFKINDATANATIONALIDENTIFICATIONNUMBER_QNAME = new QName("", "NATIONAL_IDENTIFICATION_NUMBER");
    private final static QName _GUARDIANDATAGUARDIANMIDDLENAME_QNAME = new QName("", "GUARDIAN_MIDDLE_NAME");
    private final static QName _GUARDIANDATAGUARDIANIDENTIFICATIONNUMBER_QNAME = new QName("", "GUARDIAN_IDENTIFICATION_NUMBER");
    private final static QName _ENROLLMENTDATAIRISDATA_QNAME = new QName("", "IRIS_DATA");

   
    /**
     * Create an instance of {@link ENROLLMENTDATA }
     * 
     */
    public ENROLLMENTDATA createENROLLMENTDATA() {
        return new ENROLLMENTDATA();
    }

    /**
     * Create an instance of {@link APPLICATIONDATA }
     * 
     */
    public APPLICATIONDATA createAPPLICATIONDATA() {
        return new APPLICATIONDATA();
    }

    /**
     * Create an instance of {@link DEMOGRAPHICDATA }
     * 
     */
    public DEMOGRAPHICDATA createDEMOGRAPHICDATA() {
        return new DEMOGRAPHICDATA();
    }

    /**
     * Create an instance of {@link DOCUMENTDATA }
     * 
     */
    public DOCUMENTDATA createDOCUMENTDATA() {
        return new DOCUMENTDATA();
    }

    /**
     * Create an instance of {@link RESIDENCEADDRESSDATA }
     * 
     */
    public RESIDENCEADDRESSDATA createRESIDENCEADDRESSDATA() {
        return new RESIDENCEADDRESSDATA();
    }

    /**
     * Create an instance of {@link PHYSICALFEATUREDATA }
     * 
     */
    public PHYSICALFEATUREDATA createPHYSICALFEATUREDATA() {
        return new PHYSICALFEATUREDATA();
    }

    /**
     * Create an instance of {@link DISABILITYDATA }
     * 
     */
    public DISABILITYDATA createDISABILITYDATA() {
        return new DISABILITYDATA();
    }

    /**
     * Create an instance of {@link PARENTDATA }
     * 
     */
    public PARENTDATA createPARENTDATA() {
        return new PARENTDATA();
    }

    /**
     * Create an instance of {@link GUARDIANDATA }
     * 
     */
    public GUARDIANDATA createGUARDIANDATA() {
        return new GUARDIANDATA();
    }

    /**
     * Create an instance of {@link NEXTOFKINDATA }
     * 
     */
    public NEXTOFKINDATA createNEXTOFKINDATA() {
        return new NEXTOFKINDATA();
    }

    /**
     * Create an instance of {@link CARDFINANCIALDATA }
     * 
     */
    public CARDFINANCIALDATA createCARDFINANCIALDATA() {
        return new CARDFINANCIALDATA();
    }

    /**
     * Create an instance of {@link BIOMETRICDATA }
     * 
     */
    public BIOMETRICDATA createBIOMETRICDATA() {
        return new BIOMETRICDATA();
    }

    /**
     * Create an instance of {@link APPLICANTSIGNATURE }
     * 
     */
    public APPLICANTSIGNATURE createAPPLICANTSIGNATURE() {
        return new APPLICANTSIGNATURE();
    }

    /**
     * Create an instance of {@link FATHERDATA }
     * 
     */
    public FATHERDATA createFATHERDATA() {
        return new FATHERDATA();
    }

    /**
     * Create an instance of {@link MOTHERDATA }
     * 
     */
    public MOTHERDATA createMOTHERDATA() {
        return new MOTHERDATA();
    }

    /**
     * Create an instance of {@link APPLICANTNAME }
     * 
     */
    public APPLICANTNAME createAPPLICANTNAME() {
        return new APPLICANTNAME();
    }
    /**
     * Create an instance of {@link IRISDATA }
     *
     */
    public IRISDATA createIRISDATA() {
        return new IRISDATA();
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_RING_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATALEFTRINGQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATALEFTRINGQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_MIDDLE", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATARIGHTMIDDLE(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATARIGHTMIDDLE_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_THUMB", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATALEFTTHUMB(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATALEFTTHUMB_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_RING", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATARIGHTRING(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATARIGHTRING_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_RING", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATALEFTRING(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATALEFTRING_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_MIDDLE_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATARIGHTMIDDLEQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATARIGHTMIDDLEQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "USER_ID", scope = BIOMETRICDATA.class)
    public JAXBElement<String> createBIOMETRICDATAUSERID(String value) {
        return new JAXBElement<String>(_BIOMETRICDATAUSERID_QNAME, String.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_THUMB_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATALEFTTHUMBQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATALEFTTHUMBQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_RING_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATARIGHTRINGQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATARIGHTRINGQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_MIDDLE", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATALEFTMIDDLE(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATALEFTMIDDLE_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_LITTLE", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATARIGHTLITTLE(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATARIGHTLITTLE_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_INDEX", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATALEFTINDEX(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATALEFTINDEX_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_LITTLE", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATALEFTLITTLE(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATALEFTLITTLE_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_THUMB", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATARIGHTTHUMB(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATARIGHTTHUMB_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_LITTLE_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATALEFTLITTLEQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATALEFTLITTLEQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_INDEX_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATARIGHTINDEXQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATARIGHTINDEXQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_INDEX_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATALEFTINDEXQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATALEFTINDEXQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_THUMB_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATARIGHTTHUMBQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATARIGHTTHUMBQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LEFT_MIDDLE_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATALEFTMIDDLEQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATALEFTMIDDLEQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_INDEX", scope = BIOMETRICDATA.class)
    public JAXBElement<byte[]> createBIOMETRICDATARIGHTINDEX(byte[] value) {
        return new JAXBElement<byte[]>(_BIOMETRICDATARIGHTINDEX_QNAME, byte[].class, BIOMETRICDATA.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RIGHT_LITTLE_QUALITY", scope = BIOMETRICDATA.class)
    public JAXBElement<BigDecimal> createBIOMETRICDATARIGHTLITTLEQUALITY(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_BIOMETRICDATARIGHTLITTLEQUALITY_QNAME, BigDecimal.class, BIOMETRICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MOTHER_MIDDLE_NAME", scope = MOTHERDATA.class)
    public JAXBElement<String> createMOTHERDATAMOTHERMIDDLENAME(String value) {
        return new JAXBElement<String>(_MOTHERDATAMOTHERMIDDLENAME_QNAME, String.class, MOTHERDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MOTHER_MAIDEN_NAME", scope = MOTHERDATA.class)
    public JAXBElement<String> createMOTHERDATAMOTHERMAIDENNAME(String value) {
        return new JAXBElement<String>(_MOTHERDATAMOTHERMAIDENNAME_QNAME, String.class, MOTHERDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MOTHER_IDENTIFICATION_NUMBER", scope = MOTHERDATA.class)
    public JAXBElement<BigDecimal> createMOTHERDATAMOTHERIDENTIFICATIONNUMBER(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MOTHERDATAMOTHERIDENTIFICATIONNUMBER_QNAME, BigDecimal.class, MOTHERDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FATHER_MIDDLE_NAME", scope = FATHERDATA.class)
    public JAXBElement<String> createFATHERDATAFATHERMIDDLENAME(String value) {
        return new JAXBElement<String>(_FATHERDATAFATHERMIDDLENAME_QNAME, String.class, FATHERDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FATHER_IDENTIFICATION_NUMBER", scope = FATHERDATA.class)
    public JAXBElement<BigDecimal> createFATHERDATAFATHERIDENTIFICATIONNUMBER(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FATHERDATAFATHERIDENTIFICATIONNUMBER_QNAME, BigDecimal.class, FATHERDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TITLE", scope = APPLICANTNAME.class)
    public JAXBElement<String> createAPPLICANTNAMETITLE(String value) {
        return new JAXBElement<String>(_APPLICANTNAMETITLE_QNAME, String.class, APPLICANTNAME.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIDDLE_NAME", scope = APPLICANTNAME.class)
    public JAXBElement<String> createAPPLICANTNAMEMIDDLENAME(String value) {
        return new JAXBElement<String>(_APPLICANTNAMEMIDDLENAME_QNAME, String.class, APPLICANTNAME.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DEMOGRAPHICDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DEMOGRAPHIC_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<DEMOGRAPHICDATA> createENROLLMENTDATADEMOGRAPHICDATA(DEMOGRAPHICDATA value) {
        return new JAXBElement<DEMOGRAPHICDATA>(_ENROLLMENTDATADEMOGRAPHICDATA_QNAME, DEMOGRAPHICDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CARDFINANCIALDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CARD_FINANCIAL_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<CARDFINANCIALDATA> createENROLLMENTDATACARDFINANCIALDATA(CARDFINANCIALDATA value) {
        return new JAXBElement<CARDFINANCIALDATA>(_ENROLLMENTDATACARDFINANCIALDATA_QNAME, CARDFINANCIALDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RESIDENCEADDRESSDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RESIDENCE_ADDRESS_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<RESIDENCEADDRESSDATA> createENROLLMENTDATARESIDENCEADDRESSDATA(RESIDENCEADDRESSDATA value) {
        return new JAXBElement<RESIDENCEADDRESSDATA>(_ENROLLMENTDATARESIDENCEADDRESSDATA_QNAME, RESIDENCEADDRESSDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PHYSICALFEATUREDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PHYSICAL_FEATURE_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<PHYSICALFEATUREDATA> createENROLLMENTDATAPHYSICALFEATUREDATA(PHYSICALFEATUREDATA value) {
        return new JAXBElement<PHYSICALFEATUREDATA>(_ENROLLMENTDATAPHYSICALFEATUREDATA_QNAME, PHYSICALFEATUREDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NEXTOFKINDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NEXT_OF_KIN_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<NEXTOFKINDATA> createENROLLMENTDATANEXTOFKINDATA(NEXTOFKINDATA value) {
        return new JAXBElement<NEXTOFKINDATA>(_ENROLLMENTDATANEXTOFKINDATA_QNAME, NEXTOFKINDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link APPLICANTSIGNATURE }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "APPLICANT_SIGNATURE", scope = ENROLLMENTDATA.class)
    public JAXBElement<APPLICANTSIGNATURE> createENROLLMENTDATAAPPLICANTSIGNATURE(APPLICANTSIGNATURE value) {
        return new JAXBElement<APPLICANTSIGNATURE>(_ENROLLMENTDATAAPPLICANTSIGNATURE_QNAME, APPLICANTSIGNATURE.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DISABILITYDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISABILITY_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<DISABILITYDATA> createENROLLMENTDATADISABILITYDATA(DISABILITYDATA value) {
        return new JAXBElement<DISABILITYDATA>(_ENROLLMENTDATADISABILITYDATA_QNAME, DISABILITYDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PARENTDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PARENT_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<PARENTDATA> createENROLLMENTDATAPARENTDATA(PARENTDATA value) {
        return new JAXBElement<PARENTDATA>(_ENROLLMENTDATAPARENTDATA_QNAME, PARENTDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GUARDIANDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GUARDIAN_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<GUARDIANDATA> createENROLLMENTDATAGUARDIANDATA(GUARDIANDATA value) {
        return new JAXBElement<GUARDIANDATA>(_ENROLLMENTDATAGUARDIANDATA_QNAME, GUARDIANDATA.class, ENROLLMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POSTAL_CODE", scope = RESIDENCEADDRESSDATA.class)
    public JAXBElement<String> createRESIDENCEADDRESSDATAPOSTALCODE(String value) {
        return new JAXBElement<String>(_RESIDENCEADDRESSDATAPOSTALCODE_QNAME, String.class, RESIDENCEADDRESSDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADDRESS_LINE_TWO", scope = RESIDENCEADDRESSDATA.class)
    public JAXBElement<String> createRESIDENCEADDRESSDATAADDRESSLINETWO(String value) {
        return new JAXBElement<String>(_RESIDENCEADDRESSDATAADDRESSLINETWO_QNAME, String.class, RESIDENCEADDRESSDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NATIONALITY", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATANATIONALITY(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATANATIONALITY_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMPLOYMENT_STATUS", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAEMPLOYMENTSTATUS(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAEMPLOYMENTSTATUS_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BIRTH_DATE_VERIFY_P", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATABIRTHDATEVERIFYP(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATABIRTHDATEVERIFYP_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OTHER_SPOKEN_LANGUAGE", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAOTHERSPOKENLANGUAGE(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAOTHERSPOKENLANGUAGE_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "READ_WRITE_LANGUAGE", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAREADWRITELANGUAGE(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAREADWRITELANGUAGE_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EDUCATION_LEVEL", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAEDUCATIONLEVEL(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAEDUCATIONLEVEL_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link APPLICANTNAME }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "APPLICANT_NAME", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<APPLICANTNAME> createDEMOGRAPHICDATAAPPLICANTNAME(APPLICANTNAME value) {
        return new JAXBElement<APPLICANTNAME>(_DEMOGRAPHICDATAAPPLICANTNAME_QNAME, APPLICANTNAME.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MARITAL_STATUS", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAMARITALSTATUS(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAMARITALSTATUS_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SPOUSE_IDENTIFICATION_NUMBER", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<BigDecimal> createDEMOGRAPHICDATASPOUSEIDENTIFICATIONNUMBER(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DEMOGRAPHICDATASPOUSEIDENTIFICATIONNUMBER_QNAME, BigDecimal.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RESIDENCE_STATUS", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATARESIDENCESTATUS(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATARESIDENCESTATUS_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HEIGHT", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<BigDecimal> createDEMOGRAPHICDATAHEIGHT(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DEMOGRAPHICDATAHEIGHT_QNAME, BigDecimal.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NATIVE_SPOKEN_LANGUAGE", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATANATIVESPOKENLANGUAGE(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATANATIVESPOKENLANGUAGE_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EMAIL_ADDRESS", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAEMAILADDRESS(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAEMAILADDRESS_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RELIGION", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATARELIGION(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATARELIGION_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MAIDEN_NAME", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAMAIDENNAME(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAMAIDENNAME_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OTHER_NAMES", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAOTHERNAMES(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAOTHERNAMES_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROFESSION", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAPROFESSION(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAPROFESSION_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TELEPHONE_NO", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATATELEPHONENO(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATATELEPHONENO_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOMELESS_P", scope = DEMOGRAPHICDATA.class)
    public JAXBElement<String> createDEMOGRAPHICDATAHOMELESSP(String value) {
        return new JAXBElement<String>(_DEMOGRAPHICDATAHOMELESSP_QNAME, String.class, DEMOGRAPHICDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FATHERDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FATHER_DATA", scope = PARENTDATA.class)
    public JAXBElement<FATHERDATA> createPARENTDATAFATHERDATA(FATHERDATA value) {
        return new JAXBElement<FATHERDATA>(_PARENTDATAFATHERDATA_QNAME, FATHERDATA.class, PARENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MOTHERDATA }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MOTHER_DATA", scope = PARENTDATA.class)
    public JAXBElement<MOTHERDATA> createPARENTDATAMOTHERDATA(MOTHERDATA value) {
        return new JAXBElement<MOTHERDATA>(_PARENTDATAMOTHERDATA_QNAME, MOTHERDATA.class, PARENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOCUMENT_NUMBER", scope = DOCUMENTDATA.class)
    public JAXBElement<String> createDOCUMENTDATADOCUMENTNUMBER(String value) {
        return new JAXBElement<String>(_DOCUMENTDATADOCUMENTNUMBER_QNAME, String.class, DOCUMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DOCUMENT_EXPIRY_DATE", scope = DOCUMENTDATA.class)
    public JAXBElement<String> createDOCUMENTDATADOCUMENTEXPIRYDATE(String value) {
        return new JAXBElement<String>(_DOCUMENTDATADOCUMENTEXPIRYDATE_QNAME, String.class, DOCUMENTDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "POSTAL_CODE", scope = NEXTOFKINDATA.class)
    public JAXBElement<String> createNEXTOFKINDATAPOSTALCODE(String value) {
        return new JAXBElement<String>(_RESIDENCEADDRESSDATAPOSTALCODE_QNAME, String.class, NEXTOFKINDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOWN", scope = NEXTOFKINDATA.class)
    public JAXBElement<String> createNEXTOFKINDATATOWN(String value) {
        return new JAXBElement<String>(_NEXTOFKINDATATOWN_QNAME, String.class, NEXTOFKINDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LGA", scope = NEXTOFKINDATA.class)
    public JAXBElement<String> createNEXTOFKINDATALGA(String value) {
        return new JAXBElement<String>(_NEXTOFKINDATALGA_QNAME, String.class, NEXTOFKINDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NATIONAL_IDENTIFICATION_NUMBER", scope = NEXTOFKINDATA.class)
    public JAXBElement<BigDecimal> createNEXTOFKINDATANATIONALIDENTIFICATIONNUMBER(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NEXTOFKINDATANATIONALIDENTIFICATIONNUMBER_QNAME, BigDecimal.class, NEXTOFKINDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MIDDLE_NAME", scope = NEXTOFKINDATA.class)
    public JAXBElement<String> createNEXTOFKINDATAMIDDLENAME(String value) {
        return new JAXBElement<String>(_APPLICANTNAMEMIDDLENAME_QNAME, String.class, NEXTOFKINDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ADDRESS_LINE_TWO", scope = NEXTOFKINDATA.class)
    public JAXBElement<String> createNEXTOFKINDATAADDRESSLINETWO(String value) {
        return new JAXBElement<String>(_RESIDENCEADDRESSDATAADDRESSLINETWO_QNAME, String.class, NEXTOFKINDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GUARDIAN_MIDDLE_NAME", scope = GUARDIANDATA.class)
    public JAXBElement<String> createGUARDIANDATAGUARDIANMIDDLENAME(String value) {
        return new JAXBElement<String>(_GUARDIANDATAGUARDIANMIDDLENAME_QNAME, String.class, GUARDIANDATA.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GUARDIAN_IDENTIFICATION_NUMBER", scope = GUARDIANDATA.class)
    public JAXBElement<BigDecimal> createGUARDIANDATAGUARDIANIDENTIFICATIONNUMBER(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GUARDIANDATAGUARDIANIDENTIFICATIONNUMBER_QNAME, BigDecimal.class, GUARDIANDATA.class, value);
    }
    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IRISDATA }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "IRIS_DATA", scope = ENROLLMENTDATA.class)
    public JAXBElement<IRISDATA> createENROLLMENTDATAIRISDATA_QNAME(IRISDATA value) {
        return new JAXBElement<IRISDATA>(_ENROLLMENTDATAIRISDATA_QNAME, IRISDATA.class, ENROLLMENTDATA.class, value);
    }
}
