//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 11:04:50 AM WAT 
//


package com.seamfix.nimc.jaxb.personalization;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="APPLICATION_DATA"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="TRACKING_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="REGISTRATION_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ORIGINATING_CENTER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="LOADING_CENTER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="APPLICATION_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="STATION_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PRINTING_REQUIRED_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="HOME_DELIVERY_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="WEB_ENROLLMENT_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="APPLICATION_FEE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DEMOGRAPHIC_DATA"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="SURNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="MIDDLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="NATIONALITY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="BIRTH_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="BIRTH_COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="EMAIL_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="TELEPHONE_NO" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="HOMELESS_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="RESIDENCE_ADDRESS_DATA"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ADDRESS_LINE_ONE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ADDRESS_LINE_TWO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="POSTAL_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="TOWN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LGA" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="ORIGIN_DATA"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RELATION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ORIGIN_PLACE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ORIGIN_STATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ORIGIN_COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BIOMETRIC_DATA"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="LEFT_THUMB_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_INDEX_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_MIDDLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_RING_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_LITTLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_THUMB_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_INDEX_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_MIDDLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_RING_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_LITTLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_THUMB_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="LEFT_INDEX_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="LEFT_MIDDLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="LEFT_RING_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="LEFT_LITTLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="RIGHT_THUMB_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="RIGHT_INDEX_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="RIGHT_MIDDLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="RIGHT_RING_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="RIGHT_LITTLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="LEFT_THUMB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_INDEX" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_MIDDLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_RING" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LEFT_LITTLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_THUMB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_INDEX" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_MIDDLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_RING" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="RIGHT_LITTLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="PHOTOGRAPH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationdata",
    "demographicdata",
    "residenceaddressdata",
    "origindata",
    "biometricdata"
})
@XmlRootElement(name = "ENROLLMENT_DATA", namespace = ENROLLMENTDATA.ENROLLMENT_DATA_NAMESPACE)
@SuppressWarnings({"PMD.ExcessiveClassLength","PMD.NcssCount", "PMD.ExcessivePublicCount"})
public class ENROLLMENTDATA {

    static final String ENROLLMENT_DATA_NAMESPACE = "http://www.example.org/enrollment_data";
	@XmlElement(name = "APPLICATION_DATA", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
    protected ENROLLMENTDATA.APPLICATIONDATA applicationdata;
    @XmlElement(name = "DEMOGRAPHIC_DATA", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
    protected ENROLLMENTDATA.DEMOGRAPHICDATA demographicdata;
    @XmlElement(name = "RESIDENCE_ADDRESS_DATA", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
    protected ENROLLMENTDATA.RESIDENCEADDRESSDATA residenceaddressdata;
    @XmlElement(name = "ORIGIN_DATA", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
    protected ENROLLMENTDATA.ORIGINDATA origindata;
    @XmlElement(name = "BIOMETRIC_DATA", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
    protected ENROLLMENTDATA.BIOMETRICDATA biometricdata;

    /**
     * Gets the value of the applicationdata property.
     * 
     * @return
     *     possible object is
     *     {@link ENROLLMENTDATA.APPLICATIONDATA }
     *     
     */
    public ENROLLMENTDATA.APPLICATIONDATA getAPPLICATIONDATA() {
        return applicationdata;
    }

    /**
     * Sets the value of the applicationdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENROLLMENTDATA.APPLICATIONDATA }
     *     
     */
    public void setAPPLICATIONDATA(ENROLLMENTDATA.APPLICATIONDATA value) {
        this.applicationdata = value;
    }

    /**
     * Gets the value of the demographicdata property.
     * 
     * @return
     *     possible object is
     *     {@link ENROLLMENTDATA.DEMOGRAPHICDATA }
     *     
     */
    public ENROLLMENTDATA.DEMOGRAPHICDATA getDEMOGRAPHICDATA() {
        return demographicdata;
    }

    /**
     * Sets the value of the demographicdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENROLLMENTDATA.DEMOGRAPHICDATA }
     *     
     */
    public void setDEMOGRAPHICDATA(ENROLLMENTDATA.DEMOGRAPHICDATA value) {
        this.demographicdata = value;
    }

    /**
     * Gets the value of the residenceaddressdata property.
     * 
     * @return
     *     possible object is
     *     {@link ENROLLMENTDATA.RESIDENCEADDRESSDATA }
     *     
     */
    public ENROLLMENTDATA.RESIDENCEADDRESSDATA getRESIDENCEADDRESSDATA() {
        return residenceaddressdata;
    }

    /**
     * Sets the value of the residenceaddressdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENROLLMENTDATA.RESIDENCEADDRESSDATA }
     *     
     */
    public void setRESIDENCEADDRESSDATA(ENROLLMENTDATA.RESIDENCEADDRESSDATA value) {
        this.residenceaddressdata = value;
    }

    /**
     * Gets the value of the origindata property.
     * 
     * @return
     *     possible object is
     *     {@link ENROLLMENTDATA.ORIGINDATA }
     *     
     */
    public ENROLLMENTDATA.ORIGINDATA getORIGINDATA() {
        return origindata;
    }

    /**
     * Sets the value of the origindata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENROLLMENTDATA.ORIGINDATA }
     *     
     */
    public void setORIGINDATA(ENROLLMENTDATA.ORIGINDATA value) {
        this.origindata = value;
    }

    /**
     * Gets the value of the biometricdata property.
     * 
     * @return
     *     possible object is
     *     {@link ENROLLMENTDATA.BIOMETRICDATA }
     *     
     */
    public ENROLLMENTDATA.BIOMETRICDATA getBIOMETRICDATA() {
        return biometricdata;
    }

    /**
     * Sets the value of the biometricdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ENROLLMENTDATA.BIOMETRICDATA }
     *     
     */
    public void setBIOMETRICDATA(ENROLLMENTDATA.BIOMETRICDATA value) {
        this.biometricdata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="TRACKING_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="REGISTRATION_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ORIGINATING_CENTER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="LOADING_CENTER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="APPLICATION_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="STATION_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PRINTING_REQUIRED_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="HOME_DELIVERY_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="WEB_ENROLLMENT_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="APPLICATION_FEE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userid",
        "trackingid",
        "registrationdate",
        "originatingcenter",
        "loadingcenter",
        "applicationtype",
        "stationid",
        "printingrequiredp",
        "homedeliveryp",
        "webenrollmentp",
        "applicationfee"
    })
    public static class APPLICATIONDATA {

        @XmlElement(name = "USER_ID", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected BigDecimal userid;
        @XmlElement(name = "TRACKING_ID", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String trackingid;
        @XmlElement(name = "REGISTRATION_DATE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String registrationdate;
        @XmlElement(name = "ORIGINATING_CENTER", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int originatingcenter;
        @XmlElement(name = "LOADING_CENTER", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int loadingcenter;
        @XmlElement(name = "APPLICATION_TYPE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String applicationtype;
        @XmlElement(name = "STATION_ID", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String stationid;
        @XmlElement(name = "PRINTING_REQUIRED_P", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String printingrequiredp;
        @XmlElement(name = "HOME_DELIVERY_P", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String homedeliveryp;
        @XmlElement(name = "WEB_ENROLLMENT_P", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String webenrollmentp;
        @XmlElement(name = "APPLICATION_FEE", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int applicationfee;

        /**
         * Gets the value of the userid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUSERID() {
            return userid;
        }

        /**
         * Sets the value of the userid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUSERID(BigDecimal value) {
            this.userid = value;
        }

        /**
         * Gets the value of the trackingid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTRACKINGID() {
            return trackingid;
        }

        /**
         * Sets the value of the trackingid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTRACKINGID(String value) {
            this.trackingid = value;
        }

        /**
         * Gets the value of the registrationdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getREGISTRATIONDATE() {
            return registrationdate;
        }

        /**
         * Sets the value of the registrationdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setREGISTRATIONDATE(String value) {
            this.registrationdate = value;
        }

        /**
         * Gets the value of the originatingcenter property.
         * 
         */
        public int getORIGINATINGCENTER() {
            return originatingcenter;
        }

        /**
         * Sets the value of the originatingcenter property.
         * 
         */
        public void setORIGINATINGCENTER(int value) {
            this.originatingcenter = value;
        }

        /**
         * Gets the value of the loadingcenter property.
         * 
         */
        public int getLOADINGCENTER() {
            return loadingcenter;
        }

        /**
         * Sets the value of the loadingcenter property.
         * 
         */
        public void setLOADINGCENTER(int value) {
            this.loadingcenter = value;
        }

        /**
         * Gets the value of the applicationtype property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAPPLICATIONTYPE() {
            return applicationtype;
        }

        /**
         * Sets the value of the applicationtype property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAPPLICATIONTYPE(String value) {
            this.applicationtype = value;
        }

        /**
         * Gets the value of the stationid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATIONID() {
            return stationid;
        }

        /**
         * Sets the value of the stationid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATIONID(String value) {
            this.stationid = value;
        }

        /**
         * Gets the value of the printingrequiredp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPRINTINGREQUIREDP() {
            return printingrequiredp;
        }

        /**
         * Sets the value of the printingrequiredp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPRINTINGREQUIREDP(String value) {
            this.printingrequiredp = value;
        }

        /**
         * Gets the value of the homedeliveryp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHOMEDELIVERYP() {
            return homedeliveryp;
        }

        /**
         * Sets the value of the homedeliveryp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHOMEDELIVERYP(String value) {
            this.homedeliveryp = value;
        }

        /**
         * Gets the value of the webenrollmentp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWEBENROLLMENTP() {
            return webenrollmentp;
        }

        /**
         * Sets the value of the webenrollmentp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWEBENROLLMENTP(String value) {
            this.webenrollmentp = value;
        }

        /**
         * Gets the value of the applicationfee property.
         * 
         */
        public int getAPPLICATIONFEE() {
            return applicationfee;
        }

        /**
         * Sets the value of the applicationfee property.
         * 
         */
        public void setAPPLICATIONFEE(int value) {
            this.applicationfee = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="LEFT_THUMB_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_INDEX_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_MIDDLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_RING_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_LITTLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_THUMB_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_INDEX_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_MIDDLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_RING_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_LITTLE_STATUS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_THUMB_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="LEFT_INDEX_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="LEFT_MIDDLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="LEFT_RING_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="LEFT_LITTLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="RIGHT_THUMB_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="RIGHT_INDEX_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="RIGHT_MIDDLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="RIGHT_RING_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="RIGHT_LITTLE_QUALITY" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="LEFT_THUMB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_INDEX" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_MIDDLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_RING" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LEFT_LITTLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_THUMB" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_INDEX" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_MIDDLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_RING" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="RIGHT_LITTLE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="PHOTOGRAPH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userid",
        "leftthumbstatus",
        "leftindexstatus",
        "leftmiddlestatus",
        "leftringstatus",
        "leftlittlestatus",
        "rightthumbstatus",
        "rightindexstatus",
        "rightmiddlestatus",
        "rightringstatus",
        "rightlittlestatus",
        "leftthumbquality",
        "leftindexquality",
        "leftmiddlequality",
        "leftringquality",
        "leftlittlequality",
        "rightthumbquality",
        "rightindexquality",
        "rightmiddlequality",
        "rightringquality",
        "rightlittlequality",
        "leftthumb",
        "leftindex",
        "leftmiddle",
        "leftring",
        "leftlittle",
        "rightthumb",
        "rightindex",
        "rightmiddle",
        "rightring",
        "rightlittle",
        "photograph"
    })
    public static class BIOMETRICDATA {

        @XmlElement(name = "USER_ID", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected BigDecimal userid;
        @XmlElement(name = "LEFT_THUMB_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftthumbstatus;
        @XmlElement(name = "LEFT_INDEX_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftindexstatus;
        @XmlElement(name = "LEFT_MIDDLE_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftmiddlestatus;
        @XmlElement(name = "LEFT_RING_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftringstatus;
        @XmlElement(name = "LEFT_LITTLE_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftlittlestatus;
        @XmlElement(name = "RIGHT_THUMB_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightthumbstatus;
        @XmlElement(name = "RIGHT_INDEX_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightindexstatus;
        @XmlElement(name = "RIGHT_MIDDLE_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightmiddlestatus;
        @XmlElement(name = "RIGHT_RING_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightringstatus;
        @XmlElement(name = "RIGHT_LITTLE_STATUS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightlittlestatus;
        @XmlElement(name = "LEFT_THUMB_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int leftthumbquality;
        @XmlElement(name = "LEFT_INDEX_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int leftindexquality;
        @XmlElement(name = "LEFT_MIDDLE_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int leftmiddlequality;
        @XmlElement(name = "LEFT_RING_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int leftringquality;
        @XmlElement(name = "LEFT_LITTLE_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int leftlittlequality;
        @XmlElement(name = "RIGHT_THUMB_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int rightthumbquality;
        @XmlElement(name = "RIGHT_INDEX_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int rightindexquality;
        @XmlElement(name = "RIGHT_MIDDLE_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int rightmiddlequality;
        @XmlElement(name = "RIGHT_RING_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int rightringquality;
        @XmlElement(name = "RIGHT_LITTLE_QUALITY", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int rightlittlequality;
        @XmlElement(name = "LEFT_THUMB", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftthumb;
        @XmlElement(name = "LEFT_INDEX", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftindex;
        @XmlElement(name = "LEFT_MIDDLE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftmiddle;
        @XmlElement(name = "LEFT_RING", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftring;
        @XmlElement(name = "LEFT_LITTLE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String leftlittle;
        @XmlElement(name = "RIGHT_THUMB", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightthumb;
        @XmlElement(name = "RIGHT_INDEX", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightindex;
        @XmlElement(name = "RIGHT_MIDDLE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightmiddle;
        @XmlElement(name = "RIGHT_RING", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightring;
        @XmlElement(name = "RIGHT_LITTLE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String rightlittle;
        @XmlElement(name = "PHOTOGRAPH", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String photograph;

        /**
         * Gets the value of the userid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUSERID() {
            return userid;
        }

        /**
         * Sets the value of the userid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUSERID(BigDecimal value) {
            this.userid = value;
        }

        /**
         * Gets the value of the leftthumbstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTTHUMBSTATUS() {
            return leftthumbstatus;
        }

        /**
         * Sets the value of the leftthumbstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTTHUMBSTATUS(String value) {
            this.leftthumbstatus = value;
        }

        /**
         * Gets the value of the leftindexstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTINDEXSTATUS() {
            return leftindexstatus;
        }

        /**
         * Sets the value of the leftindexstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTINDEXSTATUS(String value) {
            this.leftindexstatus = value;
        }

        /**
         * Gets the value of the leftmiddlestatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTMIDDLESTATUS() {
            return leftmiddlestatus;
        }

        /**
         * Sets the value of the leftmiddlestatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTMIDDLESTATUS(String value) {
            this.leftmiddlestatus = value;
        }

        /**
         * Gets the value of the leftringstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTRINGSTATUS() {
            return leftringstatus;
        }

        /**
         * Sets the value of the leftringstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTRINGSTATUS(String value) {
            this.leftringstatus = value;
        }

        /**
         * Gets the value of the leftlittlestatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTLITTLESTATUS() {
            return leftlittlestatus;
        }

        /**
         * Sets the value of the leftlittlestatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTLITTLESTATUS(String value) {
            this.leftlittlestatus = value;
        }

        /**
         * Gets the value of the rightthumbstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTTHUMBSTATUS() {
            return rightthumbstatus;
        }

        /**
         * Sets the value of the rightthumbstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTTHUMBSTATUS(String value) {
            this.rightthumbstatus = value;
        }

        /**
         * Gets the value of the rightindexstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTINDEXSTATUS() {
            return rightindexstatus;
        }

        /**
         * Sets the value of the rightindexstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTINDEXSTATUS(String value) {
            this.rightindexstatus = value;
        }

        /**
         * Gets the value of the rightmiddlestatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTMIDDLESTATUS() {
            return rightmiddlestatus;
        }

        /**
         * Sets the value of the rightmiddlestatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTMIDDLESTATUS(String value) {
            this.rightmiddlestatus = value;
        }

        /**
         * Gets the value of the rightringstatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTRINGSTATUS() {
            return rightringstatus;
        }

        /**
         * Sets the value of the rightringstatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTRINGSTATUS(String value) {
            this.rightringstatus = value;
        }

        /**
         * Gets the value of the rightlittlestatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTLITTLESTATUS() {
            return rightlittlestatus;
        }

        /**
         * Sets the value of the rightlittlestatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTLITTLESTATUS(String value) {
            this.rightlittlestatus = value;
        }

        /**
         * Gets the value of the leftthumbquality property.
         * 
         */
        public int getLEFTTHUMBQUALITY() {
            return leftthumbquality;
        }

        /**
         * Sets the value of the leftthumbquality property.
         * 
         */
        public void setLEFTTHUMBQUALITY(int value) {
            this.leftthumbquality = value;
        }

        /**
         * Gets the value of the leftindexquality property.
         * 
         */
        public int getLEFTINDEXQUALITY() {
            return leftindexquality;
        }

        /**
         * Sets the value of the leftindexquality property.
         * 
         */
        public void setLEFTINDEXQUALITY(int value) {
            this.leftindexquality = value;
        }

        /**
         * Gets the value of the leftmiddlequality property.
         * 
         */
        public int getLEFTMIDDLEQUALITY() {
            return leftmiddlequality;
        }

        /**
         * Sets the value of the leftmiddlequality property.
         * 
         */
        public void setLEFTMIDDLEQUALITY(int value) {
            this.leftmiddlequality = value;
        }

        /**
         * Gets the value of the leftringquality property.
         * 
         */
        public int getLEFTRINGQUALITY() {
            return leftringquality;
        }

        /**
         * Sets the value of the leftringquality property.
         * 
         */
        public void setLEFTRINGQUALITY(int value) {
            this.leftringquality = value;
        }

        /**
         * Gets the value of the leftlittlequality property.
         * 
         */
        public int getLEFTLITTLEQUALITY() {
            return leftlittlequality;
        }

        /**
         * Sets the value of the leftlittlequality property.
         * 
         */
        public void setLEFTLITTLEQUALITY(int value) {
            this.leftlittlequality = value;
        }

        /**
         * Gets the value of the rightthumbquality property.
         * 
         */
        public int getRIGHTTHUMBQUALITY() {
            return rightthumbquality;
        }

        /**
         * Sets the value of the rightthumbquality property.
         * 
         */
        public void setRIGHTTHUMBQUALITY(int value) {
            this.rightthumbquality = value;
        }

        /**
         * Gets the value of the rightindexquality property.
         * 
         */
        public int getRIGHTINDEXQUALITY() {
            return rightindexquality;
        }

        /**
         * Sets the value of the rightindexquality property.
         * 
         */
        public void setRIGHTINDEXQUALITY(int value) {
            this.rightindexquality = value;
        }

        /**
         * Gets the value of the rightmiddlequality property.
         * 
         */
        public int getRIGHTMIDDLEQUALITY() {
            return rightmiddlequality;
        }

        /**
         * Sets the value of the rightmiddlequality property.
         * 
         */
        public void setRIGHTMIDDLEQUALITY(int value) {
            this.rightmiddlequality = value;
        }

        /**
         * Gets the value of the rightringquality property.
         * 
         */
        public int getRIGHTRINGQUALITY() {
            return rightringquality;
        }

        /**
         * Sets the value of the rightringquality property.
         * 
         */
        public void setRIGHTRINGQUALITY(int value) {
            this.rightringquality = value;
        }

        /**
         * Gets the value of the rightlittlequality property.
         * 
         */
        public int getRIGHTLITTLEQUALITY() {
            return rightlittlequality;
        }

        /**
         * Sets the value of the rightlittlequality property.
         * 
         */
        public void setRIGHTLITTLEQUALITY(int value) {
            this.rightlittlequality = value;
        }

        /**
         * Gets the value of the leftthumb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTTHUMB() {
            return leftthumb;
        }

        /**
         * Sets the value of the leftthumb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTTHUMB(String value) {
            this.leftthumb = value;
        }

        /**
         * Gets the value of the leftindex property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTINDEX() {
            return leftindex;
        }

        /**
         * Sets the value of the leftindex property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTINDEX(String value) {
            this.leftindex = value;
        }

        /**
         * Gets the value of the leftmiddle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTMIDDLE() {
            return leftmiddle;
        }

        /**
         * Sets the value of the leftmiddle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTMIDDLE(String value) {
            this.leftmiddle = value;
        }

        /**
         * Gets the value of the leftring property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTRING() {
            return leftring;
        }

        /**
         * Sets the value of the leftring property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTRING(String value) {
            this.leftring = value;
        }

        /**
         * Gets the value of the leftlittle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLEFTLITTLE() {
            return leftlittle;
        }

        /**
         * Sets the value of the leftlittle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLEFTLITTLE(String value) {
            this.leftlittle = value;
        }

        /**
         * Gets the value of the rightthumb property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTTHUMB() {
            return rightthumb;
        }

        /**
         * Sets the value of the rightthumb property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTTHUMB(String value) {
            this.rightthumb = value;
        }

        /**
         * Gets the value of the rightindex property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTINDEX() {
            return rightindex;
        }

        /**
         * Sets the value of the rightindex property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTINDEX(String value) {
            this.rightindex = value;
        }

        /**
         * Gets the value of the rightmiddle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTMIDDLE() {
            return rightmiddle;
        }

        /**
         * Sets the value of the rightmiddle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTMIDDLE(String value) {
            this.rightmiddle = value;
        }

        /**
         * Gets the value of the rightring property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTRING() {
            return rightring;
        }

        /**
         * Sets the value of the rightring property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTRING(String value) {
            this.rightring = value;
        }

        /**
         * Gets the value of the rightlittle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRIGHTLITTLE() {
            return rightlittle;
        }

        /**
         * Sets the value of the rightlittle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRIGHTLITTLE(String value) {
            this.rightlittle = value;
        }

        /**
         * Gets the value of the photograph property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPHOTOGRAPH() {
            return photograph;
        }

        /**
         * Sets the value of the photograph property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPHOTOGRAPH(String value) {
            this.photograph = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="SURNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="MIDDLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="NATIONALITY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="BIRTH_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="BIRTH_COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="EMAIL_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="TELEPHONE_NO" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="HOMELESS_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userid",
        "surname",
        "firstname",
        "middlename",
        "nationality",
        "birthdate",
        "birthcountry",
        "gender",
        "height",
        "emailaddress",
        "telephoneno",
        "homelessp"
    })
    public static class DEMOGRAPHICDATA {

        @XmlElement(name = "USER_ID", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected BigDecimal userid;
        @XmlElement(name = "SURNAME", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String surname;
        @XmlElement(name = "FIRST_NAME", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String firstname;
        @XmlElement(name = "MIDDLE_NAME", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String middlename;
        @XmlElement(name = "NATIONALITY", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String nationality;
        @XmlElement(name = "BIRTH_DATE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String birthdate;
        @XmlElement(name = "BIRTH_COUNTRY", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String birthcountry;
        @XmlElement(name = "GENDER", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String gender;
        @XmlElement(name = "HEIGHT", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int height;
        @XmlElement(name = "EMAIL_ADDRESS", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String emailaddress;
        @XmlElement(name = "TELEPHONE_NO", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int telephoneno;
        @XmlElement(name = "HOMELESS_P", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String homelessp;

        /**
         * Gets the value of the userid property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUSERID() {
            return userid;
        }

        /**
         * Sets the value of the userid property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUSERID(BigDecimal value) {
            this.userid = value;
        }

        /**
         * Gets the value of the surname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSURNAME() {
            return surname;
        }

        /**
         * Sets the value of the surname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSURNAME(String value) {
            this.surname = value;
        }

        /**
         * Gets the value of the firstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFIRSTNAME() {
            return firstname;
        }

        /**
         * Sets the value of the firstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFIRSTNAME(String value) {
            this.firstname = value;
        }

        /**
         * Gets the value of the middlename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMIDDLENAME() {
            return middlename;
        }

        /**
         * Sets the value of the middlename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMIDDLENAME(String value) {
            this.middlename = value;
        }

        /**
         * Gets the value of the nationality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNATIONALITY() {
            return nationality;
        }

        /**
         * Sets the value of the nationality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNATIONALITY(String value) {
            this.nationality = value;
        }

        /**
         * Gets the value of the birthdate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBIRTHDATE() {
            return birthdate;
        }

        /**
         * Sets the value of the birthdate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBIRTHDATE(String value) {
            this.birthdate = value;
        }

        /**
         * Gets the value of the birthcountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBIRTHCOUNTRY() {
            return birthcountry;
        }

        /**
         * Sets the value of the birthcountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBIRTHCOUNTRY(String value) {
            this.birthcountry = value;
        }

        /**
         * Gets the value of the gender property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGENDER() {
            return gender;
        }

        /**
         * Sets the value of the gender property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGENDER(String value) {
            this.gender = value;
        }

        /**
         * Gets the value of the height property.
         * 
         */
        public int getHEIGHT() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         */
        public void setHEIGHT(int value) {
            this.height = value;
        }

        /**
         * Gets the value of the emailaddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEMAILADDRESS() {
            return emailaddress;
        }

        /**
         * Sets the value of the emailaddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEMAILADDRESS(String value) {
            this.emailaddress = value;
        }

        /**
         * Gets the value of the telephoneno property.
         * 
         */
        public int getTELEPHONENO() {
            return telephoneno;
        }

        /**
         * Sets the value of the telephoneno property.
         * 
         */
        public void setTELEPHONENO(int value) {
            this.telephoneno = value;
        }

        /**
         * Gets the value of the homelessp property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHOMELESSP() {
            return homelessp;
        }

        /**
         * Sets the value of the homelessp property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHOMELESSP(String value) {
            this.homelessp = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="RELATION" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ORIGIN_PLACE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ORIGIN_STATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ORIGIN_COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relation",
        "originplace",
        "originstate",
        "origincountry"
    })
    public static class ORIGINDATA {

        @XmlElement(name = "RELATION", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String relation;
        @XmlElement(name = "ORIGIN_PLACE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String originplace;
        @XmlElement(name = "ORIGIN_STATE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String originstate;
        @XmlElement(name = "ORIGIN_COUNTRY", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String origincountry;

        /**
         * Gets the value of the relation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRELATION() {
            return relation;
        }

        /**
         * Sets the value of the relation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRELATION(String value) {
            this.relation = value;
        }

        /**
         * Gets the value of the originplace property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getORIGINPLACE() {
            return originplace;
        }

        /**
         * Sets the value of the originplace property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORIGINPLACE(String value) {
            this.originplace = value;
        }

        /**
         * Gets the value of the originstate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getORIGINSTATE() {
            return originstate;
        }

        /**
         * Sets the value of the originstate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORIGINSTATE(String value) {
            this.originstate = value;
        }

        /**
         * Gets the value of the origincountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getORIGINCOUNTRY() {
            return origincountry;
        }

        /**
         * Sets the value of the origincountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORIGINCOUNTRY(String value) {
            this.origincountry = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ADDRESS_LINE_ONE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ADDRESS_LINE_TWO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="POSTAL_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="TOWN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LGA" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addresslineone",
        "addresslinetwo",
        "postalcode",
        "town",
        "lga",
        "country"
    })
    public static class RESIDENCEADDRESSDATA {

        @XmlElement(name = "ADDRESS_LINE_ONE", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String addresslineone;
        @XmlElement(name = "ADDRESS_LINE_TWO", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String addresslinetwo;
        @XmlElement(name = "POSTAL_CODE", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int postalcode;
        @XmlElement(name = "TOWN", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String town;
        @XmlElement(name = "LGA", namespace = ENROLLMENT_DATA_NAMESPACE)
        protected int lga;
        @XmlElement(name = "COUNTRY", namespace = ENROLLMENT_DATA_NAMESPACE, required = true)
        protected String country;

        /**
         * Gets the value of the addresslineone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDRESSLINEONE() {
            return addresslineone;
        }

        /**
         * Sets the value of the addresslineone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDRESSLINEONE(String value) {
            this.addresslineone = value;
        }

        /**
         * Gets the value of the addresslinetwo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDRESSLINETWO() {
            return addresslinetwo;
        }

        /**
         * Sets the value of the addresslinetwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDRESSLINETWO(String value) {
            this.addresslinetwo = value;
        }

        /**
         * Gets the value of the postalcode property.
         * 
         */
        public int getPOSTALCODE() {
            return postalcode;
        }

        /**
         * Sets the value of the postalcode property.
         * 
         */
        public void setPOSTALCODE(int value) {
            this.postalcode = value;
        }

        /**
         * Gets the value of the town property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTOWN() {
            return town;
        }

        /**
         * Sets the value of the town property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTOWN(String value) {
            this.town = value;
        }

        /**
         * Gets the value of the lga property.
         * 
         */
        public int getLGA() {
            return lga;
        }

        /**
         * Sets the value of the lga property.
         * 
         */
        public void setLGA(int value) {
            this.lga = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCOUNTRY() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCOUNTRY(String value) {
            this.country = value;
        }

    }

}
