//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 08:19:57 PM WAT 
//


package com.seamfix.nimc.jaxb.personalization;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PHOTOGRAPH" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ORIGIN_STATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ADDRESS_DATA"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="POST_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                   &lt;element name="TOWN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LGA" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
 *                   &lt;element name="ADDRESS_LINE_TWO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ADDRESS_LINE_ONE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="BIRTH_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *         &lt;element name="TRACKING_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="REGISTRATION_DATE" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="NATIONAL_IDENTIFICATION_NUMBER" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="NAME"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="MIDDLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="SURNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "photograph",
    "originstate",
    "addressdata",
    "birthdate",
    "gender",
    "height",
    "trackingid",
    "registrationdate",
    "nationalidentificationnumber",
    "name"
})
@XmlRootElement(name = "personalization-data")
@SuppressWarnings({"PMD.AvoidUsingShortType","PMD.ShortClassName"})
public class PersonalizationData {

    @XmlElement(name = "PHOTOGRAPH", required = true)
    protected String photograph;
    @XmlElement(name = "ORIGIN_STATE", required = true)
    protected String originstate;
    @XmlElement(name = "ADDRESS_DATA", required = true)
    protected PersonalizationData.ADDRESSDATA addressdata;
    @XmlElement(name = "BIRTH_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthdate;
    @XmlElement(name = "GENDER", required = true)
    protected String gender;
    @XmlElement(name = "HEIGHT")
    protected short height;
    @XmlElement(name = "TRACKING_ID", required = true)
    protected String trackingid;
    @XmlElement(name = "REGISTRATION_DATE", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar registrationdate;
    @XmlElement(name = "NATIONAL_IDENTIFICATION_NUMBER")
    protected long nationalidentificationnumber;
    @XmlElement(name = "NAME", required = true)
    protected PersonalizationData.NAME name;
    @XmlAttribute(name = "valid")
    protected String valid;
    
    @XmlTransient
    protected long birthday;
    
    @XmlTransient
    protected long registrationday;

    /**
     * Gets the value of the photograph property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHOTOGRAPH() {
        return photograph;
    }

    /**
     * Sets the value of the photograph property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHOTOGRAPH(String value) {
        this.photograph = value;
    }

    /**
     * Gets the value of the originstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORIGINSTATE() {
        return originstate;
    }

    /**
     * Sets the value of the originstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORIGINSTATE(String value) {
        this.originstate = value;
    }

    /**
     * Gets the value of the addressdata property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalizationData.ADDRESSDATA }
     *     
     */
    public PersonalizationData.ADDRESSDATA getADDRESSDATA() {
        return addressdata;
    }

    /**
     * Sets the value of the addressdata property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalizationData.ADDRESSDATA }
     *     
     */
    public void setADDRESSDATA(PersonalizationData.ADDRESSDATA value) {
        this.addressdata = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBIRTHDATE() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBIRTHDATE(XMLGregorianCalendar value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENDER() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENDER(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public short getHEIGHT() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHEIGHT(short value) {
        this.height = value;
    }

    /**
     * Gets the value of the trackingid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRACKINGID() {
        return trackingid;
    }

    /**
     * Sets the value of the trackingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRACKINGID(String value) {
        this.trackingid = value;
    }

    /**
     * Gets the value of the registrationdate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getREGISTRATIONDATE() {
        return registrationdate;
    }

    /**
     * Sets the value of the registrationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setREGISTRATIONDATE(XMLGregorianCalendar value) {
        this.registrationdate = value;
    }

    /**
     * Gets the value of the nationalidentificationnumber property.
     * 
     */
    public long getNATIONALIDENTIFICATIONNUMBER() {
        return nationalidentificationnumber;
    }

    /**
     * Sets the value of the nationalidentificationnumber property.
     * 
     */
    public void setNATIONALIDENTIFICATIONNUMBER(long value) {
        this.nationalidentificationnumber = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link PersonalizationData.NAME }
     *     
     */
    public PersonalizationData.NAME getNAME() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonalizationData.NAME }
     *     
     */
    public void setNAME(PersonalizationData.NAME value) {
        this.name = value;
    }

    /**
     * Gets the value of the valid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValid() {
        return valid;
    }

    /**
     * Sets the value of the valid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValid(String value) {
        this.valid = value;
    }
    
    public long getBirthday() {
    	birthday = this.birthdate.toGregorianCalendar().getTime().getTime();
    	return birthday;
    }

    
    public void setBirthday(long birthday) {
        this.birthday = birthday;
    }
    
    public long getRegistrationday() {
    	registrationday = this.registrationdate.toGregorianCalendar().getTime().getTime();
    	return registrationday;
    }

    
    public void setRegistrationday(long registrationday) {
        this.registrationday = registrationday;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="POST_CODE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *         &lt;element name="TOWN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LGA" type="{http://www.w3.org/2001/XMLSchema}float"/&gt;
     *         &lt;element name="ADDRESS_LINE_TWO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ADDRESS_LINE_ONE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="STATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "postcode",
        "town",
        "lga",
        "addresslinetwo",
        "addresslineone",
        "state"
    })
    public static class ADDRESSDATA {

        @XmlElement(name = "POST_CODE")
        protected int postcode;
        @XmlElement(name = "TOWN", required = true)
        protected String town;
        @XmlElement(name = "LGA")
        protected float lga;
        @XmlElement(name = "ADDRESS_LINE_TWO", required = true)
        protected String addresslinetwo;
        @XmlElement(name = "ADDRESS_LINE_ONE", required = true)
        protected String addresslineone;
        @XmlElement(name = "STATE", required = true)
        protected String state;
        @XmlAttribute(name = "valid")
        protected String valid;

        /**
         * Gets the value of the postcode property.
         * 
         */
        public int getPOSTCODE() {
            return postcode;
        }

        /**
         * Sets the value of the postcode property.
         * 
         */
        public void setPOSTCODE(int value) {
            this.postcode = value;
        }

        /**
         * Gets the value of the town property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTOWN() {
            return town;
        }

        /**
         * Sets the value of the town property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTOWN(String value) {
            this.town = value;
        }

        /**
         * Gets the value of the lga property.
         * 
         */
        public float getLGA() {
            return lga;
        }

        /**
         * Sets the value of the lga property.
         * 
         */
        public void setLGA(float value) {
            this.lga = value;
        }

        /**
         * Gets the value of the addresslinetwo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDRESSLINETWO() {
            return addresslinetwo;
        }

        /**
         * Sets the value of the addresslinetwo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDRESSLINETWO(String value) {
            this.addresslinetwo = value;
        }

        /**
         * Gets the value of the addresslineone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getADDRESSLINEONE() {
            return addresslineone;
        }

        /**
         * Sets the value of the addresslineone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setADDRESSLINEONE(String value) {
            this.addresslineone = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSTATE() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSTATE(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the valid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValid(String value) {
            this.valid = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="MIDDLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SURNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="valid" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "middlename",
        "surname",
        "firstname"
    })
    public static class NAME {

        @XmlElement(name = "MIDDLE_NAME", required = true)
        protected String middlename;
        @XmlElement(name = "SURNAME", required = true)
        protected String surname;
        @XmlElement(name = "FIRST_NAME", required = true)
        protected String firstname;
        @XmlAttribute(name = "valid")
        protected String valid;

        /**
         * Gets the value of the middlename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMIDDLENAME() {
            return middlename;
        }

        /**
         * Sets the value of the middlename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMIDDLENAME(String value) {
            this.middlename = value;
        }

        /**
         * Gets the value of the surname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSURNAME() {
            return surname;
        }

        /**
         * Sets the value of the surname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSURNAME(String value) {
            this.surname = value;
        }

        /**
         * Gets the value of the firstname property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFIRSTNAME() {
            return firstname;
        }

        /**
         * Sets the value of the firstname property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFIRSTNAME(String value) {
            this.firstname = value;
        }

        /**
         * Gets the value of the valid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValid() {
            return valid;
        }

        /**
         * Sets the value of the valid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValid(String value) {
            this.valid = value;
        }

    }

}
