
package com.seamfix.integrations.nimc.stubs.verification;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IdentitySearch", targetNamespace = "http://IdentitySearch.nimc/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IdentitySearch {


    /**
     * 
     * @param password
     * @param level
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.DemoMapPermission
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPermissionByLevel", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetPermissionByLevel")
    @ResponseWrapper(localName = "getPermissionByLevelResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetPermissionByLevelResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getPermissionByLevelRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getPermissionByLevelResponse")
    public DemoMapPermission getPermissionByLevel(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "level", targetNamespace = "")
                    int level);

    /**
     * 
     * @param level
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.DemoMapPermission
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPermissionByLevel2", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetPermissionByLevel2")
    @ResponseWrapper(localName = "getPermissionByLevel2Response", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetPermissionByLevel2Response")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getPermissionByLevel2Request", output = "http://IdentitySearch.nimc/IdentitySearch/getPermissionByLevel2Response")
    public DemoMapPermission getPermissionByLevel2(
            @WebParam(name = "level", targetNamespace = "")
                    int level);

    /**
     * 
     * @param password
     * @param userid
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.AccessObject
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccessObject", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAccessObject")
    @ResponseWrapper(localName = "getAccessObjectResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAccessObjectResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getAccessObjectRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getAccessObjectResponse")
    public AccessObject getAccessObject(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid);

    /**
     * 
     * @param loginmessage
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.AccessTypeMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccessList", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAccessList")
    @ResponseWrapper(localName = "getAccessListResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAccessListResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getAccessListRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getAccessListResponse")
    public AccessTypeMsg getAccessList(
            @WebParam(name = "loginmessage", targetNamespace = "")
                    LoginMessage loginmessage);

    /**
     * 
     * @param requestType
     * @param loginmessage
     * @param userid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.BooleanMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "grantaccessType", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GrantaccessType")
    @ResponseWrapper(localName = "grantaccessTypeResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GrantaccessTypeResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/grantaccessTypeRequest", output = "http://IdentitySearch.nimc/IdentitySearch/grantaccessTypeResponse")
    public BooleanMsg grantaccessType(
            @WebParam(name = "loginmessage", targetNamespace = "")
                    LoginMessage loginmessage,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "requestType", targetNamespace = "")
                    RequestTypeEnum requestType);

    /**
     * 
     * @param requestType
     * @param loginmessage
     * @param userid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.BooleanMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeaccessType", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.RevokeaccessType")
    @ResponseWrapper(localName = "revokeaccessTypeResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.RevokeaccessTypeResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/revokeaccessTypeRequest", output = "http://IdentitySearch.nimc/IdentitySearch/revokeaccessTypeResponse")
    public BooleanMsg revokeaccessType(
            @WebParam(name = "loginmessage", targetNamespace = "")
                    LoginMessage loginmessage,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "requestType", targetNamespace = "")
                    RequestTypeEnum requestType);

    /**
     * 
     * @param level
     * @param loginmessage
     * @param userid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.BooleanMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "grantaccessDemo", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GrantaccessDemo")
    @ResponseWrapper(localName = "grantaccessDemoResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GrantaccessDemoResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/grantaccessDemoRequest", output = "http://IdentitySearch.nimc/IdentitySearch/grantaccessDemoResponse")
    public BooleanMsg grantaccessDemo(
            @WebParam(name = "loginmessage", targetNamespace = "")
                    LoginMessage loginmessage,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "level", targetNamespace = "")
                    int level);

    /**
     * 
     * @param level
     * @param loginmessage
     * @param userid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.BooleanMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "revokeaccessDemo", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.RevokeaccessDemo")
    @ResponseWrapper(localName = "revokeaccessDemoResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.RevokeaccessDemoResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/revokeaccessDemoRequest", output = "http://IdentitySearch.nimc/IdentitySearch/revokeaccessDemoResponse")
    public BooleanMsg revokeaccessDemo(
            @WebParam(name = "loginmessage", targetNamespace = "")
                    LoginMessage loginmessage,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "level", targetNamespace = "")
                    int level);

    /**
     * 
     * @param machineAddress
     * @param fingerStringInBase64
     * @param password
     * @param nin
     * @param pos
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFinger", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.VerifyFinger")
    @ResponseWrapper(localName = "verifyFingerResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.VerifyFingerResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/verifyFingerRequest", output = "http://IdentitySearch.nimc/IdentitySearch/verifyFingerResponse")
    public SearchResponse verifyFinger(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "nin", targetNamespace = "")
                    String nin,
            @WebParam(name = "fingerStringInBase64", targetNamespace = "")
                    String fingerStringInBase64,
            @WebParam(name = "pos", targetNamespace = "")
                    String pos);

    /**
     * 
     * @param machineAddress
     * @param fingerStringInBase64
     * @param password
     * @param nin
     * @param pos
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyFingerWithData", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.VerifyFingerWithData")
    @ResponseWrapper(localName = "verifyFingerWithDataResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.VerifyFingerWithDataResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/verifyFingerWithDataRequest", output = "http://IdentitySearch.nimc/IdentitySearch/verifyFingerWithDataResponse")
    public SearchResponseDemo verifyFingerWithData(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "nin", targetNamespace = "")
                    String nin,
            @WebParam(name = "fingerStringInBase64", targetNamespace = "")
                    String fingerStringInBase64,
            @WebParam(name = "pos", targetNamespace = "")
                    String pos);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param fingerStringInBase64Two
     * @param fingerStringInBase64One
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compareFinger", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CompareFinger")
    @ResponseWrapper(localName = "compareFingerResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CompareFingerResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/compareFingerRequest", output = "http://IdentitySearch.nimc/IdentitySearch/compareFingerResponse")
    public SearchResponse compareFinger(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "fingerStringInBase64One", targetNamespace = "")
                    String fingerStringInBase64One,
            @WebParam(name = "fingerStringInBase64Two", targetNamespace = "")
                    String fingerStringInBase64Two);

    /**
     * 
     * @param ids
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validIDs", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.ValidIDs")
    @ResponseWrapper(localName = "validIDsResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.ValidIDsResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/validIDsRequest", output = "http://IdentitySearch.nimc/IdentitySearch/validIDsResponse")
    public SearchResponseDemo2 validIDs(
            @WebParam(name = "ids", targetNamespace = "")
                    List<String> ids);

    /**
     * 
     * @param password
     * @param firstname
     * @param phone
     * @param surname
     * @param arg10
     * @param userid
     * @param orgid
     * @param email
     * @param arg9
     * @param username
     * @param status
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoginMessage
     */
    @WebMethod(operationName = "UpdateUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateUser", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UpdateUser")
    @ResponseWrapper(localName = "UpdateUserResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UpdateUserResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/UpdateUserRequest", output = "http://IdentitySearch.nimc/IdentitySearch/UpdateUserResponse")
    public LoginMessage updateUser(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "surname", targetNamespace = "")
                    String surname,
            @WebParam(name = "firstname", targetNamespace = "")
                    String firstname,
            @WebParam(name = "phone", targetNamespace = "")
                    String phone,
            @WebParam(name = "email", targetNamespace = "")
                    String email,
            @WebParam(name = "status", targetNamespace = "")
                    Status status,
            @WebParam(name = "arg9", targetNamespace = "")
                    AccessObject arg9,
            @WebParam(name = "arg10", targetNamespace = "")
                    int arg10);

    /**
     * 
     * @param password
     * @param firstname
     * @param phone
     * @param surname
     * @param arg10
     * @param userid
     * @param orgid
     * @param email
     * @param arg9
     * @param username
     * @param status
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoginMessage
     */
    @WebMethod(operationName = "UpdateUserAndResetPassword")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateUserAndResetPassword", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UpdateUserAndResetPassword")
    @ResponseWrapper(localName = "UpdateUserAndResetPasswordResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UpdateUserAndResetPasswordResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/UpdateUserAndResetPasswordRequest", output = "http://IdentitySearch.nimc/IdentitySearch/UpdateUserAndResetPasswordResponse")
    public LoginMessage updateUserAndResetPassword(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid,
            @WebParam(name = "surname", targetNamespace = "")
                    String surname,
            @WebParam(name = "firstname", targetNamespace = "")
                    String firstname,
            @WebParam(name = "phone", targetNamespace = "")
                    String phone,
            @WebParam(name = "email", targetNamespace = "")
                    String email,
            @WebParam(name = "status", targetNamespace = "")
                    Status status,
            @WebParam(name = "arg9", targetNamespace = "")
                    AccessObject arg9,
            @WebParam(name = "arg10", targetNamespace = "")
                    int arg10);

    /**
     * 
     * @param password
     * @param firstname
     * @param phone
     * @param surname
     * @param orgid
     * @param email
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoginMessage
     */
    @WebMethod(operationName = "UpdateUserSELF")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "UpdateUserSELF", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UpdateUserSELF")
    @ResponseWrapper(localName = "UpdateUserSELFResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UpdateUserSELFResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/UpdateUserSELFRequest", output = "http://IdentitySearch.nimc/IdentitySearch/UpdateUserSELFResponse")
    public LoginMessage updateUserSELF(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "surname", targetNamespace = "")
                    String surname,
            @WebParam(name = "firstname", targetNamespace = "")
                    String firstname,
            @WebParam(name = "phone", targetNamespace = "")
                    String phone,
            @WebParam(name = "email", targetNamespace = "")
                    String email);

    /**
     * 
     * @param arg3
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.UsersMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetUserByName")
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetUserByNameResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getUserByNameRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getUserByNameResponse")
    public UsersMsg getUserByName(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3);

    /**
     * 
     * @param arg3
     * @param password
     * @param arg4
     * @param orgid
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkDuplicateUserForORGs", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CheckDuplicateUserForORGs")
    @ResponseWrapper(localName = "checkDuplicateUserForORGsResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CheckDuplicateUserForORGsResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/checkDuplicateUserForORGsRequest", output = "http://IdentitySearch.nimc/IdentitySearch/checkDuplicateUserForORGsResponse")
    public String checkDuplicateUserForORGs(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4);

    /**
     * 
     * @param password
     * @param userid
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.UsersMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserByID", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetUserByID")
    @ResponseWrapper(localName = "getUserByIDResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetUserByIDResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getUserByIDRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getUserByIDResponse")
    public UsersMsg getUserByID(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.UsersMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUsers", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAllUsers")
    @ResponseWrapper(localName = "getAllUsersResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAllUsersResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getAllUsersRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getAllUsersResponse")
    public UsersMsg getAllUsers(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param machineAddress
     * @param fingerStringInBase64
     * @param fingercode
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByFingerAndPosition", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByFingerAndPosition")
    @ResponseWrapper(localName = "searchByFingerAndPositionResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByFingerAndPositionResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByFingerAndPositionRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByFingerAndPositionResponse")
    public SearchResponse searchByFingerAndPosition(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "fingerStringInBase64", targetNamespace = "")
                    String fingerStringInBase64,
            @WebParam(name = "fingercode", targetNamespace = "")
                    String fingercode);

    /**
     * 
     * @param centralId
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignature", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetSignature")
    @ResponseWrapper(localName = "getSignatureResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetSignatureResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getSignatureRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getSignatureResponse")
    public SearchResponse getSignature(
            @WebParam(name = "centralId", targetNamespace = "")
                    String centralId);

    /**
     * 
     * @param machineAddress
     * @param fingerStringInBase64
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByOneFingerRecursive", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByOneFingerRecursive")
    @ResponseWrapper(localName = "searchByOneFingerRecursiveResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByOneFingerRecursiveResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByOneFingerRecursiveRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByOneFingerRecursiveResponse")
    public SearchResponse searchByOneFingerRecursive(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "fingerStringInBase64", targetNamespace = "")
                    String fingerStringInBase64);

    /**
     * 
     * @param asaUsername
     * @param receiverid
     * @param requestType
     * @param units
     * @param orgid
     * @param asaPasswd
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "TransferUnits")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "TransferUnits", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransferUnits")
    @ResponseWrapper(localName = "TransferUnitsResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransferUnitsResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/TransferUnitsRequest", output = "http://IdentitySearch.nimc/IdentitySearch/TransferUnitsResponse")
    public String transferUnits(
            @WebParam(name = "asa_username", targetNamespace = "")
                    String asaUsername,
            @WebParam(name = "asa_passwd", targetNamespace = "")
                    String asaPasswd,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "receiverid", targetNamespace = "")
                    String receiverid,
            @WebParam(name = "request_type", targetNamespace = "")
                    String requestType,
            @WebParam(name = "units", targetNamespace = "")
                    int units);

    /**
     * 
     * @param asaUsername
     * @param requestType
     * @param orgid
     * @param asaPasswd
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.Units
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAvailableUnits", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAvailableUnits")
    @ResponseWrapper(localName = "getAvailableUnitsResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAvailableUnitsResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getAvailableUnitsRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getAvailableUnitsResponse")
    public Units getAvailableUnits(
            @WebParam(name = "asa_username", targetNamespace = "")
                    String asaUsername,
            @WebParam(name = "asa_passwd", targetNamespace = "")
                    String asaPasswd,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "request_type", targetNamespace = "")
                    String requestType);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoginMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.LoginResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/loginRequest", output = "http://IdentitySearch.nimc/IdentitySearch/loginResponse")
    public LoginMessage login(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param password
     * @param userid
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.CheckerObject
     */
    @WebMethod(operationName = "ApproveUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ApproveUser", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.ApproveUser")
    @ResponseWrapper(localName = "ApproveUserResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.ApproveUserResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/ApproveUserRequest", output = "http://IdentitySearch.nimc/IdentitySearch/ApproveUserResponse")
    public CheckerObject approveUser(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid);

    /**
     * 
     * @param password
     * @param userid
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.CheckerObject
     */
    @WebMethod(operationName = "DeclineUser")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "DeclineUser", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.DeclineUser")
    @ResponseWrapper(localName = "DeclineUserResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.DeclineUserResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/DeclineUserRequest", output = "http://IdentitySearch.nimc/IdentitySearch/DeclineUserResponse")
    public CheckerObject declineUser(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "userid", targetNamespace = "")
                    String userid);

    /**
     * 
     * @param password
     * @param npassword
     * @param orgid
     * @param username
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "passwordchange", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.Passwordchange")
    @ResponseWrapper(localName = "passwordchangeResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.PasswordchangeResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/passwordchangeRequest", output = "http://IdentitySearch.nimc/IdentitySearch/passwordchangeResponse")
    public boolean passwordchange(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "npassword", targetNamespace = "")
                    String npassword);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoadedUnits
     */
    @WebMethod(operationName = "AllTransfersByASA")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "AllTransfersByASA", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.AllTransfersByASA")
    @ResponseWrapper(localName = "AllTransfersByASAResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.AllTransfersByASAResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/AllTransfersByASARequest", output = "http://IdentitySearch.nimc/IdentitySearch/AllTransfersByASAResponse")
    public LoadedUnits allTransfersByASA(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param firstname
     * @param asaPwd
     * @param orgAddress
     * @param orgid
     * @param orgUsername
     * @param arg17
     * @param arg18
     * @param asaUsername
     * @param nin
     * @param arg19
     * @param orgname
     * @param arg13
     * @param phone
     * @param arg14
     * @param surname
     * @param arg15
     * @param arg16
     * @param arg20
     * @param arg11
     * @param arg12
     * @param email
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoginMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccountORGChecker", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CreateAccountORGChecker")
    @ResponseWrapper(localName = "createAccountORGCheckerResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CreateAccountORGCheckerResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/createAccountORGCheckerRequest", output = "http://IdentitySearch.nimc/IdentitySearch/createAccountORGCheckerResponse")
    public LoginMessage createAccountORGChecker(
            @WebParam(name = "asa_username", targetNamespace = "")
                    String asaUsername,
            @WebParam(name = "asa_pwd", targetNamespace = "")
                    String asaPwd,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "org_username", targetNamespace = "")
                    String orgUsername,
            @WebParam(name = "orgname", targetNamespace = "")
                    String orgname,
            @WebParam(name = "org_address", targetNamespace = "")
                    String orgAddress,
            @WebParam(name = "phone", targetNamespace = "")
                    String phone,
            @WebParam(name = "surname", targetNamespace = "")
                    String surname,
            @WebParam(name = "firstname", targetNamespace = "")
                    String firstname,
            @WebParam(name = "nin", targetNamespace = "")
                    String nin,
            @WebParam(name = "email", targetNamespace = "")
                    String email,
            @WebParam(name = "arg11", targetNamespace = "")
                    AccessObject arg11,
            @WebParam(name = "arg12", targetNamespace = "")
                    Status arg12,
            @WebParam(name = "arg13", targetNamespace = "")
                    int arg13,
            @WebParam(name = "arg14", targetNamespace = "")
                    String arg14,
            @WebParam(name = "arg15", targetNamespace = "")
                    String arg15,
            @WebParam(name = "arg16", targetNamespace = "")
                    String arg16,
            @WebParam(name = "arg17", targetNamespace = "")
                    String arg17,
            @WebParam(name = "arg18", targetNamespace = "")
                    String arg18,
            @WebParam(name = "arg19", targetNamespace = "")
                    String arg19,
            @WebParam(name = "arg20", targetNamespace = "")
                    String arg20);

    /**
     * 
     * @param userUsername
     * @param firstname
     * @param orgAddress
     * @param orgid
     * @param orgUsername
     * @param nin
     * @param orgname
     * @param arg13
     * @param phone
     * @param surname
     * @param orgPwd
     * @param arg11
     * @param arg12
     * @param email
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoginMessage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccountUSER", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CreateAccountUSER")
    @ResponseWrapper(localName = "createAccountUSERResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.CreateAccountUSERResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/createAccountUSERRequest", output = "http://IdentitySearch.nimc/IdentitySearch/createAccountUSERResponse")
    public LoginMessage createAccountUSER(
            @WebParam(name = "org_username", targetNamespace = "")
                    String orgUsername,
            @WebParam(name = "org_pwd", targetNamespace = "")
                    String orgPwd,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "user_username", targetNamespace = "")
                    String userUsername,
            @WebParam(name = "orgname", targetNamespace = "")
                    String orgname,
            @WebParam(name = "org_address", targetNamespace = "")
                    String orgAddress,
            @WebParam(name = "phone", targetNamespace = "")
                    String phone,
            @WebParam(name = "surname", targetNamespace = "")
                    String surname,
            @WebParam(name = "firstname", targetNamespace = "")
                    String firstname,
            @WebParam(name = "nin", targetNamespace = "")
                    String nin,
            @WebParam(name = "email", targetNamespace = "")
                    String email,
            @WebParam(name = "arg11", targetNamespace = "")
                    AccessObject arg11,
            @WebParam(name = "arg12", targetNamespace = "")
                    Status arg12,
            @WebParam(name = "arg13", targetNamespace = "")
                    int arg13);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param nin
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByNIN", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByNIN")
    @ResponseWrapper(localName = "searchByNINResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByNINResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByNINRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByNINResponse")
    public SearchResponseDemo searchByNIN(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "nin", targetNamespace = "")
                    String nin);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param nin
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByDocumentNo", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByDocumentNo")
    @ResponseWrapper(localName = "searchByDocumentNoResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByDocumentNoResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByDocumentNoRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByDocumentNoResponse")
    public SearchResponseDemo searchByDocumentNo(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "nin", targetNamespace = "")
                    String nin);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param id
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByID", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByID")
    @ResponseWrapper(localName = "searchByIDResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByIDResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByIDRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByIDResponse")
    public SearchResponseDemo searchByID(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "id", targetNamespace = "")
                    String id);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param id
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByIDs", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByIDs")
    @ResponseWrapper(localName = "searchByIDsResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByIDsResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByIDsRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByIDsResponse")
    public SearchResponseDemo searchByIDs(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "id", targetNamespace = "")
                    List<String> id);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param heigthrange
     * @param demodata
     * @param birthrange
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByDemo", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByDemo")
    @ResponseWrapper(localName = "searchByDemoResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByDemoResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoResponse")
    public SearchResponseDemo2 searchByDemo(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "demodata", targetNamespace = "")
                    DemoData demodata,
            @WebParam(name = "birthrange", targetNamespace = "")
                    BirthDateRangeType birthrange,
            @WebParam(name = "heigthrange", targetNamespace = "")
                    HeigthRangeType heigthrange);

    /**
     * 
     * @param machineAddress
     * @param password
     * @param heigthrange
     * @param demodata
     * @param birthrange
     * @param veriNIN
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.SearchResponseDemo2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchByDemoNIN", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByDemoNIN")
    @ResponseWrapper(localName = "searchByDemoNINResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.SearchByDemoNINResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoNINRequest", output = "http://IdentitySearch.nimc/IdentitySearch/searchByDemoNINResponse")
    public SearchResponseDemo2 searchByDemoNIN(
            @WebParam(name = "MachineAddress", targetNamespace = "")
                    String machineAddress,
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "demodata", targetNamespace = "")
                    DemoData demodata,
            @WebParam(name = "birthrange", targetNamespace = "")
                    BirthDateRangeType birthrange,
            @WebParam(name = "heigthrange", targetNamespace = "")
                    HeigthRangeType heigthrange,
            @WebParam(name = "veriNIN", targetNamespace = "")
                    String veriNIN);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.LoadedUnits
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTopUpUnits", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAllTopUpUnits")
    @ResponseWrapper(localName = "getAllTopUpUnitsResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.GetAllTopUpUnitsResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/getAllTopUpUnitsRequest", output = "http://IdentitySearch.nimc/IdentitySearch/getAllTopUpUnitsResponse")
    public LoadedUnits getAllTopUpUnits(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @param searchUserid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.UnitSummaryMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unitsummaryASA", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UnitsummaryASA")
    @ResponseWrapper(localName = "unitsummaryASAResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UnitsummaryASAResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/unitsummaryASARequest", output = "http://IdentitySearch.nimc/IdentitySearch/unitsummaryASAResponse")
    public UnitSummaryMsg unitsummaryASA(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "search_userid", targetNamespace = "")
                    String searchUserid);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.UnitSummaryMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unitsummaryORG", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UnitsummaryORG")
    @ResponseWrapper(localName = "unitsummaryORGResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.UnitsummaryORGResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/unitsummaryORGRequest", output = "http://IdentitySearch.nimc/IdentitySearch/unitsummaryORGResponse")
    public UnitSummaryMsg unitsummaryORG(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @param searchUserid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.TransactionCountMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactioncountORG", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountORG")
    @ResponseWrapper(localName = "transactioncountORGResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountORGResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactioncountORGRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactioncountORGResponse")
    public TransactionCountMsg transactioncountORG(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "search_userid", targetNamespace = "")
                    String searchUserid);

    /**
     * 
     * @param fromm
     * @param password
     * @param too
     * @param orgid
     * @param username
     * @param searchUserid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.TransactionCountMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactioncountRangeORG", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountRangeORG")
    @ResponseWrapper(localName = "transactioncountRangeORGResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountRangeORGResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactioncountRangeORGRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactioncountRangeORGResponse")
    public TransactionCountMsg transactioncountRangeORG(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "search_userid", targetNamespace = "")
                    String searchUserid,
            @WebParam(name = "fromm", targetNamespace = "")
                    String fromm,
            @WebParam(name = "too", targetNamespace = "")
                    String too);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.TransactionCountMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactioncountUSER", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountUSER")
    @ResponseWrapper(localName = "transactioncountUSERResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountUSERResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactioncountUSERRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactioncountUSERResponse")
    public TransactionCountMsg transactioncountUSER(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param password
     * @param fromDdMmYyyy
     * @param toDdMmYyyy
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.TransactionCountMsg
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactioncountRangeUSER", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountRangeUSER")
    @ResponseWrapper(localName = "transactioncountRangeUSERResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactioncountRangeUSERResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactioncountRangeUSERRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactioncountRangeUSERResponse")
    public TransactionCountMsg transactioncountRangeUSER(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "from_dd_mm_yyyy", targetNamespace = "")
                    String fromDdMmYyyy,
            @WebParam(name = "to_dd_mm_yyyy", targetNamespace = "")
                    String toDdMmYyyy);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @param searchUserid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.Transactions
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactionLogsORG", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsORG")
    @ResponseWrapper(localName = "transactionLogsORGResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsORGResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsORGRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsORGResponse")
    public Transactions transactionLogsORG(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "search_userid", targetNamespace = "")
                    String searchUserid);

    /**
     * 
     * @param password
     * @param fromDdMmYyyy
     * @param toDdMmYyyy
     * @param orgid
     * @param username
     * @param searchUserid
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.Transactions
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactionLogsRangeORG", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsRangeORG")
    @ResponseWrapper(localName = "transactionLogsRangeORGResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsRangeORGResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsRangeORGRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsRangeORGResponse")
    public Transactions transactionLogsRangeORG(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "search_userid", targetNamespace = "")
                    String searchUserid,
            @WebParam(name = "from_dd_mm_yyyy", targetNamespace = "")
                    String fromDdMmYyyy,
            @WebParam(name = "to_dd_mm_yyyy", targetNamespace = "")
                    String toDdMmYyyy);

    /**
     * 
     * @param password
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.Transactions
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactionLogsUSER", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsUSER")
    @ResponseWrapper(localName = "transactionLogsUSERResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsUSERResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsUSERRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsUSERResponse")
    public Transactions transactionLogsUSER(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid);

    /**
     * 
     * @param password
     * @param fromDdMmYyyy
     * @param toDdMmYyyy
     * @param orgid
     * @param username
     * @return
     *     returns com.seamfix.integrations.nimc.stubs.Transactions
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transactionLogsRangeUSER", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsRangeUSER")
    @ResponseWrapper(localName = "transactionLogsRangeUSERResponse", targetNamespace = "http://IdentitySearch.nimc/", className = "com.seamfix.integrations.nimc.stubs.TransactionLogsRangeUSERResponse")
    @Action(input = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsRangeUSERRequest", output = "http://IdentitySearch.nimc/IdentitySearch/transactionLogsRangeUSERResponse")
    public Transactions transactionLogsRangeUSER(
            @WebParam(name = "username", targetNamespace = "")
                    String username,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "orgid", targetNamespace = "")
                    String orgid,
            @WebParam(name = "from_dd_mm_yyyy", targetNamespace = "")
                    String fromDdMmYyyy,
            @WebParam(name = "to_dd_mm_yyyy", targetNamespace = "")
                    String toDdMmYyyy);

}
