//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.12 at 12:26:06 PM WAT 
//


package com.seamfix.nimc.wsdl.stubs.personalization;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.seamfix.nimc.jaxb.personalization.DeliveryFeedback;


/**
 * <p>Java class for recieveDeliveryFeedbackResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="recieveDeliveryFeedbackResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deliveryFeedback" type="{http://frontend.ws.nimc.gov.ng/}deliveryFeedback" minOccurs="0" form="qualified"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "recieveDeliveryFeedbackResponse", propOrder = {
    "deliveryFeedback"
})
public class RecieveDeliveryFeedbackResponse {

    @XmlElement(namespace = "http://frontend.ws.nimc.gov.ng/")
    protected DeliveryFeedback deliveryFeedback;

    /**
     * Gets the value of the deliveryFeedback property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryFeedback }
     *     
     */
    public DeliveryFeedback getDeliveryFeedback() {
        return deliveryFeedback;
    }

    /**
     * Sets the value of the deliveryFeedback property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryFeedback }
     *     
     */
    public void setDeliveryFeedback(DeliveryFeedback value) {
        this.deliveryFeedback = value;
    }

}
