//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 11:03:22 AM WAT 
//


package com.seamfix.nimc.jaxb.enrollment;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for APPLICATION_DATAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="APPLICATION_DATAType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TRACKING_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="REGISTRATION_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ORIGINATING_CENTER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="LOADING_CENTER" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="APPLICATION_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STATION_ID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PRINTING_REQUIRED_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HOME_DELIVERY_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="WEB_ENROLLMENT_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="APPLICATION_FEE" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "APPLICATION_DATAType", propOrder = {
    "userid",
    "trackingid",
    "registrationdate",
    "originatingcenter",
    "loadingcenter",
    "applicationtype",
    "stationid",
    "printingrequiredp",
    "homedeliveryp",
    "webenrollmentp",
    "applicationfee"
})
public class APPLICATIONDATAType {

    @XmlElement(name = "USER_ID", required = true)
    public BigDecimal userid;
    @XmlElement(name = "TRACKING_ID", required = true)
    public String trackingid;
    @XmlElement(name = "REGISTRATION_DATE", required = true)
    public String registrationdate;
    @XmlElement(name = "ORIGINATING_CENTER")
    public int originatingcenter;
    @XmlElement(name = "LOADING_CENTER")
    public int loadingcenter;
    @XmlElement(name = "APPLICATION_TYPE", required = true)
    public String applicationtype;
    @XmlElement(name = "STATION_ID", required = true)
    public String stationid;
    @XmlElement(name = "PRINTING_REQUIRED_P", required = true)
    public String printingrequiredp;
    @XmlElement(name = "HOME_DELIVERY_P", required = true)
    public String homedeliveryp;
    @XmlElement(name = "WEB_ENROLLMENT_P", required = true)
    public String webenrollmentp;
    @XmlElement(name = "APPLICATION_FEE")
    public int applicationfee;

    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUSERID(BigDecimal value) {
        this.userid = value;
    }

    /**
     * Gets the value of the trackingid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRACKINGID() {
        return trackingid;
    }

    /**
     * Sets the value of the trackingid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRACKINGID(String value) {
        this.trackingid = value;
    }

    /**
     * Gets the value of the registrationdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREGISTRATIONDATE() {
        return registrationdate;
    }

    /**
     * Sets the value of the registrationdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREGISTRATIONDATE(String value) {
        this.registrationdate = value;
    }

    /**
     * Gets the value of the originatingcenter property.
     * 
     */
    public int getORIGINATINGCENTER() {
        return originatingcenter;
    }

    /**
     * Sets the value of the originatingcenter property.
     * 
     */
    public void setORIGINATINGCENTER(int value) {
        this.originatingcenter = value;
    }

    /**
     * Gets the value of the loadingcenter property.
     * 
     */
    public int getLOADINGCENTER() {
        return loadingcenter;
    }

    /**
     * Sets the value of the loadingcenter property.
     * 
     */
    public void setLOADINGCENTER(int value) {
        this.loadingcenter = value;
    }

    /**
     * Gets the value of the applicationtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPPLICATIONTYPE() {
        return applicationtype;
    }

    /**
     * Sets the value of the applicationtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPPLICATIONTYPE(String value) {
        this.applicationtype = value;
    }

    /**
     * Gets the value of the stationid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATIONID() {
        return stationid;
    }

    /**
     * Sets the value of the stationid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATIONID(String value) {
        this.stationid = value;
    }

    /**
     * Gets the value of the printingrequiredp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRINTINGREQUIREDP() {
        return printingrequiredp;
    }

    /**
     * Sets the value of the printingrequiredp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRINTINGREQUIREDP(String value) {
        this.printingrequiredp = value;
    }

    /**
     * Gets the value of the homedeliveryp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMEDELIVERYP() {
        return homedeliveryp;
    }

    /**
     * Sets the value of the homedeliveryp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMEDELIVERYP(String value) {
        this.homedeliveryp = value;
    }

    /**
     * Gets the value of the webenrollmentp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWEBENROLLMENTP() {
        return webenrollmentp;
    }

    /**
     * Sets the value of the webenrollmentp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWEBENROLLMENTP(String value) {
        this.webenrollmentp = value;
    }

    /**
     * Gets the value of the applicationfee property.
     * 
     */
    public int getAPPLICATIONFEE() {
        return applicationfee;
    }

    /**
     * Sets the value of the applicationfee property.
     * 
     */
    public void setAPPLICATIONFEE(int value) {
        this.applicationfee = value;
    }

}
