//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 11:03:22 AM WAT 
//


package com.seamfix.nimc.jaxb.enrollment;

import java.math.BigDecimal;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DEMOGRAPHIC_DATAType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DEMOGRAPHIC_DATAType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="USER_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="SURNAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="MIDDLE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NATIONALITY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BIRTH_DATE" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BIRTH_COUNTRY" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="GENDER" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="HEIGHT" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="EMAIL_ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TELEPHONE_NO" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="HOMELESS_P" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DEMOGRAPHIC_DATAType", propOrder = {
    "userid",
    "title",
    "surname",
    "firstname",
    "middlename",
    "nationality",
    "birthdate",
    "birthcountry",
    "gender",
    "height",
    "emailaddress",
    "telephoneno",
    "homelessp"
})
public class DEMOGRAPHICDATAType {

    @XmlElement(name = "USER_ID", required = true)
    public BigDecimal userid;
    @XmlElement(name = "TITLE", required = false)
    public String title;
    @XmlElement(name = "SURNAME", required = true)
    public String surname;
    @XmlElement(name = "FIRST_NAME", required = true)
    public String firstname;
    @XmlElement(name = "MIDDLE_NAME", required = true)
    public String middlename;
    @XmlElement(name = "NATIONALITY", required = true)
    public String nationality;
    @XmlElement(name = "BIRTH_DATE", required = true)
    public String birthdate;
    @XmlElement(name = "BIRTH_COUNTRY", required = true)
    public String birthcountry;
    @XmlElement(name = "GENDER", required = true)
    public String gender;
    @XmlElement(name = "HEIGHT")
    public int height = 0;
    @XmlElement(name = "EMAIL_ADDRESS", required = true)
    public String emailaddress;
    @XmlElement(name = "TELEPHONE_NO")
    public String telephoneno;
    @XmlElement(name = "HOMELESS_P", required = true)
    public String homelessp;
    
    /**
     * Gets the value of the userid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUSERID() {
        return userid;
    }

    /**
     * Sets the value of the userid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUSERID(BigDecimal value) {
        this.userid = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSURNAME() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSURNAME(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNAME(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the middlename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMIDDLENAME() {
        return middlename;
    }

    /**
     * Sets the value of the middlename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMIDDLENAME(String value) {
        this.middlename = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNATIONALITY() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNATIONALITY(String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIRTHDATE() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIRTHDATE(String value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the birthcountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIRTHCOUNTRY() {
        return birthcountry;
    }

    /**
     * Sets the value of the birthcountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIRTHCOUNTRY(String value) {
        this.birthcountry = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENDER() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENDER(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the height property.
     * 
     */
    public int getHEIGHT() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     */
    public void setHEIGHT(int value) {
        this.height = value;
    }

    /**
     * Gets the value of the emailaddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMAILADDRESS() {
        return emailaddress;
    }

    /**
     * Sets the value of the emailaddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMAILADDRESS(String value) {
        this.emailaddress = value;
    }

    /**
     * Gets the value of the telephoneno property.
     * 
     */
    public String getTELEPHONENO() {
        return telephoneno;
    }

    /**
     * Sets the value of the telephoneno property.
     * 
     */
    public void setTELEPHONENO(String value) {
        this.telephoneno = value;
    }

    /**
     * Gets the value of the homelessp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHOMELESSP() {
        return homelessp;
    }

    /**
     * Sets the value of the homelessp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHOMELESSP(String value) {
        this.homelessp = value;
    }
    
    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public String getTITLE() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTITLE(String value) {
        this.title = value;
    }

}
