//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.11 at 11:03:22 AM WAT 
//


package com.seamfix.nimc.jaxb.enrollment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.seamfix.nimc.jaxb.enrollment2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
@SuppressWarnings("PMD.UnnecessaryConstructor")
public class ObjectFactory {

    private final static QName _ENROLLMENTDATA_QNAME = new QName("", "ENROLLMENT_DATA");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.seamfix.nimc.jaxb.enrollment2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ENROLLMENTDATAType }
     * 
     */
    public ENROLLMENTDATAType createENROLLMENTDATAType() {
        return new ENROLLMENTDATAType();
    }

    /**
     * Create an instance of {@link BIOMETRICDATAType }
     * 
     */
    public BIOMETRICDATAType createBIOMETRICDATAType() {
        return new BIOMETRICDATAType();
    }

    /**
     * Create an instance of {@link ORIGINDATAType }
     * 
     */
    public ORIGINDATAType createORIGINDATAType() {
        return new ORIGINDATAType();
    }

    /**
     * Create an instance of {@link RESIDENCEADDRESSDATAType }
     * 
     */
    public RESIDENCEADDRESSDATAType createRESIDENCEADDRESSDATAType() {
        return new RESIDENCEADDRESSDATAType();
    }

    /**
     * Create an instance of {@link DEMOGRAPHICDATAType }
     * 
     */
    public DEMOGRAPHICDATAType createDEMOGRAPHICDATAType() {
        return new DEMOGRAPHICDATAType();
    }

    /**
     * Create an instance of {@link APPLICATIONDATAType }
     * 
     */
    public APPLICATIONDATAType createAPPLICATIONDATAType() {
        return new APPLICATIONDATAType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ENROLLMENTDATAType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ENROLLMENT_DATA")
    public JAXBElement<ENROLLMENTDATAType> createENROLLMENTDATA(ENROLLMENTDATAType value) {
        return new JAXBElement<ENROLLMENTDATAType>(_ENROLLMENTDATA_QNAME, ENROLLMENTDATAType.class, null, value);
    }

}
