
package com.seamfix.nimc.wsdl.stubs.javaee.enrollment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IdentitySearch", targetNamespace = "http://IdentitySearch.nimc/", wsdlLocation = "file:/Users/morakinyoakinkunmi/Dev/IdentitySearch/IdentitySearch.wsdl")
public class IdentitySearch_Service
    extends Service
{

    private final static URL IDENTITYSEARCH_WSDL_LOCATION;
    private final static WebServiceException IDENTITYSEARCH_EXCEPTION;
    private final static QName IDENTITYSEARCH_QNAME = new QName("http://IdentitySearch.nimc/", "IdentitySearch");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/morakinyoakinkunmi/Dev/IdentitySearch/IdentitySearch.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDENTITYSEARCH_WSDL_LOCATION = url;
        IDENTITYSEARCH_EXCEPTION = e;
    }

    public IdentitySearch_Service() {
        super(__getWsdlLocation(), IDENTITYSEARCH_QNAME);
    }

    public IdentitySearch_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDENTITYSEARCH_QNAME, features);
    }

    public IdentitySearch_Service(URL wsdlLocation) {
        super(wsdlLocation, IDENTITYSEARCH_QNAME);
    }

    public IdentitySearch_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDENTITYSEARCH_QNAME, features);
    }

    public IdentitySearch_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IdentitySearch_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IdentitySearch
     */
    @WebEndpoint(name = "IdentitySearchPort")
    public IdentitySearch getIdentitySearchPort() {
        return super.getPort(new QName("http://IdentitySearch.nimc/", "IdentitySearchPort"), IdentitySearch.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IdentitySearch
     */
    @WebEndpoint(name = "IdentitySearchPort")
    public IdentitySearch getIdentitySearchPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://IdentitySearch.nimc/", "IdentitySearchPort"), IdentitySearch.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IDENTITYSEARCH_EXCEPTION!= null) {
            throw IDENTITYSEARCH_EXCEPTION;
        }
        return IDENTITYSEARCH_WSDL_LOCATION;
    }

}
