
package com.seamfix.nimc.wsdl.stubs.javaee.recieve.enrollment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataReceptionService", targetNamespace = "http://frontend.ws.nimc.gov.ng/", wsdlLocation = "http://13.56.69.207:8090/nimcdataupload/DataReception?wsdl")
public class DataReceptionService
    extends Service
{

    private final static URL DATARECEPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATARECEPTIONSERVICE_EXCEPTION;
    private final static QName DATARECEPTIONSERVICE_QNAME = new QName("http://frontend.ws.nimc.gov.ng/", "DataReceptionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://13.56.69.207:8090/nimcdataupload/DataReception?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATARECEPTIONSERVICE_WSDL_LOCATION = url;
        DATARECEPTIONSERVICE_EXCEPTION = e;
    }

    public DataReceptionService() {
        super(__getWsdlLocation(), DATARECEPTIONSERVICE_QNAME);
    }

    public DataReceptionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATARECEPTIONSERVICE_QNAME, features);
    }

    public DataReceptionService(URL wsdlLocation) {
        super(wsdlLocation, DATARECEPTIONSERVICE_QNAME);
    }

    public DataReceptionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATARECEPTIONSERVICE_QNAME, features);
    }

    public DataReceptionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataReceptionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataReception
     */
    @WebEndpoint(name = "DataReceptionPort")
    public DataReception getDataReceptionPort() {
        return super.getPort(new QName("http://frontend.ws.nimc.gov.ng/", "DataReceptionPort"), DataReception.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataReception
     */
    @WebEndpoint(name = "DataReceptionPort")
    public DataReception getDataReceptionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://frontend.ws.nimc.gov.ng/", "DataReceptionPort"), DataReception.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATARECEPTIONSERVICE_EXCEPTION!= null) {
            throw DATARECEPTIONSERVICE_EXCEPTION;
        }
        return DATARECEPTIONSERVICE_WSDL_LOCATION;
    }

}
