
package com.seamfix.nimc.wsdl.stubs.javaee.recieve.enrollment;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidXMLDataException", targetNamespace = "http://frontend.ws.nimc.gov.ng/")
public class InvalidXMLDataException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidXMLDataException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidXMLDataException_Exception(String message, InvalidXMLDataException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidXMLDataException_Exception(String message, InvalidXMLDataException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ng.gov.nimc.ws.frontend.InvalidXMLDataException
     */
    public InvalidXMLDataException getFaultInfo() {
        return faultInfo;
    }

}
